hashicorp/react-components

packages/combobox/assets/icon-dropdown-gray.svg
packages/combobox/docs.mdx
packages/combobox/field/index.tsx
packages/combobox/index.test.js
packages/combobox/index.tsx
packages/combobox/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1200392284811676/1200454406603165/f)
🔍 [Preview Link](https://react-components-git-jmadd-react-combobox-qa-hashicorp.vercel.app/components/combobox)
---
Please select one (**required**)
<details>
<summary>Release Notes (<strong>required</strong>)</summary>
</details>
---

[Combobox] Add tests & run additional QA

---

package-lock.json
package.json
packages/content/package.json
packages/content/style.css

🎟️ [Asana Task](https://app.asana.com/0/1200299211779896/1200573612919572)
🔍 [Preview Link](https://react-components-git-kscontent-visited-links-hashicorp.vercel.app/components/content)
---
This PR adds `:visited` styles to inline links to be a nice standard purple. This is a part of the learn 'user tracking' project to help communicate where folks have been when navigating between tutorials. In checking in with design, they are cool with this being a global change across all docs sites as well. 
Please select one (**required**)
<details>
<summary>Release Notes (<strong>required</strong>)</summary>
</details>
---

style(content): adds visited link styles

---

packages/consent-manager/package-lock.json
packages/consent-manager/package.json

---
I manually [bumped to a major version](https://github.com/hashicorp/react-components/commit/e6e66b7eafe609436b50794ee3dd60ab0b0fb6e5#diff-bf034a8045b25a8ec9b9a6afb4d99a74389dc8af0839f6c9bf1ba0e5d10a6705R4) and want to let Lerna do it so we keep a clean version history. 
1

Fix incorrect Consent Manager version bump

---

swingset-extensions/usage-details/partials/project-list-item/project-list-item.module.css
swingset-extensions/usage-details/project-list.js

---
Updates the usage details entry for `nextjs-scripts` to point to the correct nested package.
1

fix(UsageDetails): update nextjs-scripts usage details

---

packages/search/README.md

---
Updates the Algolia setup instructions to include more detailed notes on the correct ACL configuration for the public and private keys.

Add notes on correct ACL config for algolia keys

---

.changeset/itchy-teachers-chew.md
package-lock.json
packages/min-100-layout/LICENSE
packages/min-100-layout/README.md
packages/min-100-layout/docs.mdx
packages/min-100-layout/index.test.js
packages/min-100-layout/index.tsx
packages/min-100-layout/package-lock.json
packages/min-100-layout/package.json
packages/min-100-layout/props.js
packages/min-100-layout/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1200392284811676/1200892636887647/f)
🔍 [Preview Link](https://react-components-git-zsmin-100-layout-component-hashicorp.vercel.app/components/min100layout)
---
This PR adds a `@hashicorp/react-min-100-layout` component. This layout component is designed for use in `_app.tsx` or in top-level layouts, and ensures pages with footers will occupy the full viewport height even if their main page content is not as tall.
One example use case, where the layout would likely look much more natural if the main content occupied enough space to push the footer lower on the page:
https://boundary-git-fork-zchsh-zstest-packer-openapi-docs-hashicorp.vercel.app/api-docs-by-service
Learn already implements a similar approach with one-off global styles: …

feat(min-100-layout): add Min100Layout component

---

.changeset/twelve-peaches-wonder.md
packages/product-download-page/index.tsx

---
It has been requested that ent mode download pages not be indexed by search engines - this adds the change directly to this component.

set noindex for enterprise downloads pages

---

.changeset/config.json
.github/workflows/canary-release.yml
README.md
package.json

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200828549856250/f)
---
Adds label based canary releases for PRs, see https://github.com/hashicorp/nextjs-scripts/pull/204 for some additional details on the setup!

feat: adds label-based canary releases

---

.changeset/dirty-jars-work.md
package-lock.json
package.json
packages/version-select/.npmignore
packages/version-select/LICENSE
packages/version-select/docs.mdx
packages/version-select/index.test.tsx
packages/version-select/index.tsx
packages/version-select/package.json
packages/version-select/props.js
packages/version-select/util.test.ts
packages/version-select/util.ts

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200934847586304/f)
🔍 [Preview Link](https://react-components-git-kevin-version-select-hashicorp.vercel.app/)
---
This adds a `<VersionSelect>` component for navigating to and from `latest` and versioned docs

feat(version-select): Create `VersionSelect`

---

.changeset/eighty-cobras-vanish.md
packages/docs-page/components/version-alert/index.jsx
packages/docs-page/index.tsx
packages/docs-page/package.json
packages/version-select/CHANGELOG.md
packages/version-select/package.json

---
Renames `@hashicorp/version-select` to `@hashicorp/react-version-select` to align with the rest of our packages. We'v got some transpile tooling that relies on the `react-` prefix, so gotta add that back!
I'm not exactly sure how this will play with changesets, I might have to do a manual publish here.
Published here: https://npmjs.com/package/@hashicorp/react-version-select

chore: rename @hashicorp/version-select to @hashicorp/react-version-select

---

.changeset/tame-horses-joke.md
package-lock.json
packages/docs-page/package.json

---
We inadvertently removed the `@hashicorp/versioned-docs` dependency here, but it's still referenced so we actually need it!

chore: adds back versioned-docs dep

---

.changeset/green-shoes-refuse.md
packages/button/theme.module.css
packages/hero/carousel.js
packages/hero/carousel.module.css
packages/hero/index.js
packages/hero/props.js
packages/hero/style.module.css

---
Updating to css modules on Boundary and running into a few small things with the CSS modules upgrade.
For button:
- Fixes the `tertiary`/`neutral` variant/brand combo to render with black text as expected (I think?)
For hero:
- Updates styles to add back missing light background styles, which updates the text and carousel elements to look better on light backgrounds.

fix: button tertiary/neutral and hero light bg

---

.changeset/kind-fans-exercise.md
package-lock.json
packages/docs-page/package.json

---
Depend on the latest version of `@hashicorp/platform-docs-mdx` to ensure that we aren't pulling in old versions of our components.

Adds updating platform-doc-mdx package with more recent dependencies

---

.changeset/nice-ties-peel.md
packages/hero/index.js

---
Make the nested `Alert` in `Hero` have the opposite text color of what the `backgroundTheme` prop is specified as.

fix(Hero): update alert text color

---

.changeset/small-roses-appear.md
packages/version-select/index.test.tsx
packages/version-select/index.tsx

fix(version-select): path splicing bug

---

.changeset/small-dingos-change.md
package-lock.json
packages/docs-sidenav/fixtures/nav-data.json
packages/docs-sidenav/index.js
packages/docs-sidenav/types.ts
packages/docs-sidenav/utils/filter-content.js

🔍 [Preview Link](https://react-components-e8inu5aoi-hashicorp.vercel.app/components/docssidenav)
---
We need the capability to add small headlines to the sidenav for Terraform, this is a nice simple implementation of it.

DocsSidenav - add headline option

---

.changeset/curvy-squids-perform.md
packages/docs-page/server/generate-static-paths.ts

---
This removes a log statement that was breaking minor updates

fix: log statement violating minor release

---

.changeset/long-sheep-explode.md
packages/docs-page/components/search-bar/index.jsx
packages/search/style.module.css

---
Fixing search styles for DocsPage:
Before:
After:

fix: fix up search styles for docs page

---

.changeset/fuzzy-pumpkins-camp.md
.changeset/thick-sheep-return.md
packages/button/theme.module.css

🎟️ [Asana Task](https://app.asana.com/0/346384260719996/1201195620938226/f)
🔍 [Preview Link](https://react-components-git-zsfix-button-size-subnav-18ba7b-hashicorp.vercel.app)
📖 [Storybook showing fixed alignment in Subnav](https://react-components-storybook.vercel.app/?path=/story/components-subnav--with-surrounding-content&args=titleLink.text:waypoint;menuItems[0]._isActiveUrl:false;menuItems[1].submenu[0]._isActiveUrl:false;menuItems[1].submenu[1]._isActiveUrl:false;menuItems[1].submenu[2]._isActiveUrl:false;menuItems[2]._isActiveUrl:true;menuItems[4]._isActiveUrl:false;menuItems[5]._isActiveUrl:false)
---
This PR fixes an issue in `@hashicorp/react-button` where `small` buttons had incorrect padding that resulted in a height of `41px` rather than `40px`. Main symptom of this issue was …

fix(button): tweak small button padding to fix alignment in subnav

---

babel.config.js
jest.config.js
package-lock.json
package.json
packages/combobox/index.test.jsx
packages/use-cases/index.js

---
Use swc to transform code for jest, hopefully resulting in faster test runs.
From what I can see in the list of recent test runs in Circle, this change improves the jest run time by ~15-20% on average. The test run itself is quite quick, so it's only a few seconds here, but a definite improvement nonetheless.

feat: use swc to transform for jest

---

.changeset/eighty-forks-battle.md
packages/docs-sidenav/index.js

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201378049617080)
---
This adds a missing `key` prop

chore(docs-sidenav): add missing key prop

---

.changeset/purple-moose-bake.md
packages/docs-page/server/index.ts

---
Ensure that the existing `generateStaticPaths` method can work without having to supply a `product` parameter.

fix(docs-page): Ensure generateStaticPaths works without product

---

.changeset/ten-rivers-nail.md
packages/code-block/mdx/index.js
packages/code-block/partials/code-block-config/index.js

---
Update internal CodeBlock checks to work with MDX v2. MDX no longer passes an `mdxType` prop to the components it renders, so we've gotta look at the actual element type.

feat(code-block): updates to support rendering MDX v2

---

.changeset/wicked-years-clean.md
packages/code-block/partials/code-tabs/index.js

---
Updating the valid element types for `CodeTabs` to include those which are rendered by MDX v2.

feat: update check in CodeTabs so it works with MDX v2 output

---

.changeset/olive-lions-matter.md
packages/docs-page/server/index.ts
packages/docs-page/server/loaders/file-system.ts
packages/docs-page/server/loaders/remote-content.ts

- fix: use `this.opts`
- chore: changeset
---

refactor(docs-page): pass `scope` down to MDX renderer

---

.changeset/witty-geese-promise.md
packages/docs-page/server/loaders/remote-content.ts

---
Dynamo may return an empty string, resulting in:

fix(docs-page): remove `??` for `displayValue`

---

.changeset/dull-kiwis-clean.md
package-lock.json
package.json
packages/subnav/partials/TitleLink/index.js

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1201456213834120)
* 🔍 [Preview Vault](https://react-components-pm4b5hruj-hashicorp.vercel.app/components/subnav?id=NTY2ODI5MDcw&values=IjxTdWJuYXZcbiAgdGl0bGVMaW5rPXt7IHRleHQ6ICdIYXNoaUNvcnAgVmF1bHQnLCB1cmw6ICcjJyB9fVxuICBtZW51SXRlbXM9e1tcbiAgICB7IHRleHQ6ICdMaW5rIE9uZScsIHVybDogJyMnfSxcbiAgICB7IHRleHQ6ICdMaW5rIFR3bycsIHVybDogJyMnfSxcbiAgICB7IHRleHQ6ICdMaW5rIFRocmVlJywgdXJsOiAnIyd9XG4gIF19XG4gIGN0YUxpbmtzPXtbXG4gICAgeyB0ZXh0OiAnQ1RBIEJ1dHRvbicsIHVybDogJyMnIH1cbiAgXX1cbi8%2BIg%3D%3D)
* 🔍 [Preview Consul](https://react-components-pm4b5hruj-hashicorp.vercel.app/components/subnav?id=NTY2ODI5MDcw&values=IjxTdWJuYXZcbiAgdGl0bGVMaW5rPXt7IHRleHQ6ICdIYXNoaUNvcnAgQ29uc3VsJywgdXJsOiAnIycgfX1cbiAgbWVudUl0ZW1zPXtbXG4gICAgeyB0ZXh0OiAnTGluayBPbmUnLC …

[Subnav] Adds vault/consul attributed logo to logo dictionary

---

.changeset/old-tables-train.md
package-lock.json
package.json
packages/subnav/package.json

[Subnav] Fixes camelcase package within subnav

---

.changeset/friendly-hornets-warn.md
packages/code-block/partials/snippet-bar/style.module.css
packages/code-block/style.module.css
packages/docs-page/style.module.css
packages/hashi-stack-menu/hashi-stack-menu.module.css
packages/search/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1199972122039455/1201377046756941/f)
---
This PR hides certain UI elements that aren't useful when printing.
- `@hashicorp/react-hashi-stack-menu`
- Hides the entire menu
- `@hashicorp/react-code-block`
- Hides the "Copy" button
- `@hashicorp/react-docs-page`
- Hides the "Jump to Section" control
- Hides the "Edit this page" control
- `@hashicorp/react-search`
- Hides the entire search box

enhancement: Hide UI elements that aren't useful when printing

---

.changeset/chatty-adults-sell.md
packages/hashi-stack-menu/stack-group/index.jsx

🔍 [Preview Link](https://react-components-git-nqfix-imports-hashistackmenu-hashicorp.vercel.app)
---
This PR fixes imports in `<HashiStackMenu />`.

fix: <HashiStackMenu /> imports

---

.changeset/silly-onions-unite.md
packages/subnav/partials/TitleLink/index.js
packages/subnav/partials/TitleLink/style.module.css

🔍 [Preview Link](https://react-components-git-ac-subnav-attr-logo-sizing-hashicorp.vercel.app/components/subnav?id=NTY2ODI5MDcw&values=IjxTdWJuYXZcbiAgdGl0bGVMaW5rPXt7IHRleHQ6ICdIYXNoaUNvcnAgVmF1bHQnLCB1cmw6ICcjJyB9fVxuICBtZW51SXRlbXM9e1tcbiAgICB7IHRleHQ6ICdMaW5rIE9uZScsIHVybDogJyMnfSxcbiAgICB7IHRleHQ6ICdMaW5rIFR3bycsIHVybDogJyMnfSxcbiAgICB7IHRleHQ6ICdMaW5rIFRocmVlJywgdXJsOiAnIyd9XG4gIF19XG4gIGN0YUxpbmtzPXtbXG4gICAgeyB0ZXh0OiAnQ1RBIEJ1dHRvbicsIHVybDogJyMnIH1cbiAgXX1cbi8%2BIg%3D%3D)
---
Design request to increase the size of attributed logos to make HashiCorp label legible.

[Subnav] increases attr logo sizing

---

.changeset/warm-olives-worry.md
packages/docs-page/package.json
packages/markdown-page/package.json

---
Bumps `@hashicorp/platform-markdown-utils` to get the latest and greatest a11y features!

chore: update @hashicorp/platform-markdown-utils

---

.changeset/early-pandas-travel.md
packages/search/tools.js

---
By default, `glob` won't recurse symlinks when the `**` file pattern is used, so we need to explicitly ask that it do so.

Follow symlinks when generating search objects

---

.changeset/mighty-snails-shake.md
packages/docs-page/index.tsx

chore(docs-page): move default `showVersionSelect` prop

---

.changeset/strange-snakes-sniff.md
package-lock.json
packages/subnav/partials/MenuItemsDefault/style.module.css
packages/subnav/partials/MenuItemsOverflow/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/346384260719996/1201528364381379/f)
🔍 [Preview Link](https://react-components-git-nqadd-underline-to-subnav-links-hashicorp.vercel.app/components/subnav)
---
This PR adds underlines on hover to elements with the `.submenuItem` class in `react-subnav`. This PR also updates `package-lock.json` in the root directory.

enh.(subnav): Add underline to submenuItem elements

---

packages/docs-page/style.module.css

---
Potentially fixes https://github.com/hashicorp/vault/issues/13350
Tested in saucelabs, breaking down [the shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) seems to resolve the issue.

Fix a bug in older firefox versions

---

.changeset/odd-eyes-crash.md
packages/subnav/partials/TitleLink/index.js
packages/subnav/partials/TitleLink/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/346384260719996/1201461699398493/f)
🔍 [Preview Link](https://react-components-git-nqsubnav-add-attributed-logos-hashicorp.vercel.app/components/subnav)
---
This PR adds attributed logo options to the logo dictionary in `<TitleLink />`.

enh(Subnav): Add remaining attributed logos to TitleLink logo dict

---

.changeset/khaki-mice-fail.md
packages/content/styles/table.module.css
packages/docs-page/package.json

🎟️ [Asana Task](https://app.asana.com/0/1200392284811676/1201476871035778)
---
Allow tables to overflow to prevent layouts from breaking
https://user-images.githubusercontent.com/825855/148272860-52722471-5cf0-4361-a818-2adf237af84a.mp4

fix: content table overflow

---

.changeset/light-bats-live.md
packages/product-download-page/server.ts
packages/product-download-page/utils/__tests__/fetch-with-retry.test.ts
packages/product-download-page/utils/fetch-with-retry.ts

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201390712246181/f)
---
Adds a fetch retry with a delay when fetching releases data from releases.hashicorp.com to hopefully alleviate some failed website deploys and issue triage which happens immediately after a product release.

feat(downloads): add fetch retry with delay when fetching releases data

---

README.md
swingset-extensions/usage-details/project-list.js

---
Link to our managed sourcegraph instance, instead of our self-hosted one. I've also updated the environment variable in Vercel.

chore: update sourcegraph URL

---

docs/color.mdx
package-lock.json
package.json

🔍 [Preview Link](https://react-components-git-ambupgrade-swingset-to-latest-hashicorp.vercel.app)
---
This PR upgrades swingset to `0.11.0`, the latest as of today! 🥳 See [release](https://github.com/hashicorp/swingset/releases/tag/0.11.0) for those details.
It also replaces a `<pre>` on `/docs/color` that was causing this error:
```
Server Error
Error: Found <pre> element in MDX with more than one child: ["Colors tokens provided by @hashicorp/mktg-global-styles:",{"type":{},"key":".1","ref":null,"props":{"originalType":"br","mdxType":"br"},"_owner":null,"_store":{}},{"type":{},"key":".2","ref":null,"props":{"style":{"color":"inherit","textDecoration":"underline"},"href":"https://github.com/hashicorp/mktg-global-styles/blob/main/custom-properties/color.css","originalType":"a","mdxType":"a" …
```

Upgrading swingset to latest

---

swingset-extensions/usage-details/project-list.js

---
`terraform-website-next` has been archived in favor of `terraform-website`, so this PR replaces the former with the latter.

chore: replace terraform-website-next with terraform-website

---

.changeset/mean-crabs-jam.md
packages/content/styles/table.module.css

🔍 [Preview Link](https://react-components-git-dsth-no-left-align-hashicorp.vercel.app/components/content?id=LTEyMjU5MjYwNTA&values=IjxDb250ZW50XG4gIHByb2R1Y3Q9J3RlcnJhZm9ybSdcbiAgY29udGVudD17PHRhYmxlPjx0cj48dGg%2BaGVsbG88L3RoPjwvdHI%2BPHRyPjx0ZD5oZWxsbyB0aGVyZSBmcmllbmQ8L3RkPjwvdHI%2BPC90YWJsZT59XG4vPiI%3D)
---
This removes the default `text-align: left;` rule for table headers, allowing authors to align their headers whichever way sparks joy. By default, table headers will now be center aligned.

Remove enforced left-alignment for table headers

---

.changeset/eleven-days-check.md
package-lock.json
packages/case-study-slider/docs.mdx
packages/case-study-slider/index.js

🔍 [Preview Swingset Link](https://react-components-git-jmpatch-case-study-slider-hashicorp.vercel.app/components/casestudyslider)
🔍 [Prod Swingset Link](https://react-components.vercel.app/components/casestudyslider)
---
We got a report about a missing `href` on https://www.hashicorp.com/products/terraform/self-service-infrastructure within this component.
This PR patches a [regression on `<CaseStudySlider />`](https://github.com/hashicorp/react-components/pull/303/files#diff-4a1e06ffc11d15f2965946dc8966170080b8de583df380f1be15009388c5963eL165-L178) for cases where the link is meant to be produced from a `slug` on a given resource item in the CMS

Patch missing link in `<CaseStudySlider />`

---

.changeset/bright-meals-marry.md
packages/button/index.tsx
packages/button/package.json

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201197410794282/f)
🔍 [Preview Link](https://react-components-git-dsbutton-link-prop-hashicorp.vercel.app/)
---
This PR uses `next/link` to render all links for `Button` since recent versions of Next.js can appropriately handle external links passed to `next/link`, and will also fallback to a server-side navigation if the requested URL can't be resolved using a client-side navigation.

Render all links with `next/link`

---

.changeset/green-beers-trade.md
package-lock.json
packages/docs-page/package.json

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200794405240290/f)
🔍 [Preview Link](https://react-components-git-zsbump-docs-page-mdx-hashicorp.vercel.app)
---
This PR bumps the `@hashicorp/platform-docs-mdx` dependency in `@hashicorp/react-docs-page` in order to pull in a fix for a Firefox-specific manual copy-and-paste issue, as described and fixed in https://github.com/hashicorp/react-components/pull/503.

fix(docs-page): bumps docs-mdx for code-block fix

---

packages/badge/style.module.css

🎨 [Figma](https://www.figma.com/file/7cYgDM618stjYUHDqAfRec/Components?node-id=211%3A719)
🔍 [Preview Link](https://react-components-git-acbadge-color-hashicorp.vercel.app/components/badge)
---
Update neutral secondary color:
Update black secondary color:

chore(Badge): adjust neutral and black badge secondary colors

---

.changeset/plenty-scissors-travel.md

🔍 [Preview Link](https://react-components-git-acbadge-release-hashicorp.vercel.app/components/badge)
---
Initial release of the new `<Badge />` component.

feat(Badge): Initial release

---

.changeset/healthy-cups-tie.md
packages/head/index.tsx
packages/head/seo.test.js
packages/head/seo.tsx

---
This PR adds a new function export to `react-head` that exposes a `renderMetaTags` function for use with DatoCMS SEO attributes.
Given the following attributes from Dato:
```json
[
{
"attributes": null,
"content": "Vault by HashiCorp",
"tag": "title"
},
{
"attributes": {
"property": "og:title",
"content": "Vault by HashiCorp"
},
"content": null,
"tag": "meta"
},
{
"attributes": {
"name": "twitter:title",
"content": "Vault by HashiCorp"
},
"content": null,
"tag": "meta"
}
]
```
Calling `renderMetaTags(seo)` will return the following structure:
```jsx
<title>Vault by HashiCorp</title>
<meta property="og:title" name="twitter:title" content="Vault by HashiCorp" />
```
It performs attribute …

Add `renderMetaTags` function

---

packages/consent-manager/index.tsx

---
In recent versions of Node, the TypeScript type for `events` doesn't have a constructable default export. This PR updates our import to use a named import instead.
This PR targets the `re.round-button-corners` branch to simplify testing.

Fix EventEmitter import

---

package-lock.json
package.json
prettier.config.js

---
---
- https://app.asana.com/0/0/1201759225888759

chore: bump @hashicorp/platform-cli

---

.github/workflows/release.yml

bump node 15 to 16

---

.changeset/eight-donuts-burn.md
packages/badge/index.tsx
packages/badge/types.ts

🔍 [Preview Link](https://react-components-git-acbadge-types-hashicorp.vercel.app/components/badge)
---
Allow consumers to import types for badge component.

chore(Badge): export types

---

packages/code-block/docs.mdx

---
This PR fixes a docs issue where the sample code and actual component didn't match for arbitrary CodeTabs titles.

docs: fix CodeTabs sample

---

next.config.js
packages/author-byline/docs.mdx
packages/author-byline/index.test.js
packages/author-byline/index.tsx
packages/author-byline/package.json
packages/author-byline/props.js
packages/author-byline/style.module.css
packages/author-byline/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1202026147841458)
🔍 [Preview Link](https://react-components-git-accomponent-author-byline-hashicorp.vercel.app/components/authorbyline)
🎨 [Figma](https://www.figma.com/file/7cYgDM618stjYUHDqAfRec/Components?node-id=153%3A135)
---
Adding new `<AuthorByline />` component

feat(component): `<AuthorByline />`

---

package-lock.json
packages/quote/docs.mdx
packages/quote/index.test.js
packages/quote/index.tsx
packages/quote/package.json
packages/quote/props.js
packages/quote/style.module.css
packages/quote/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202026147841446/1202035806517042)
🔍 [Preview Link](https://react-components-k5ygd24re-hashicorp.vercel.app/components/quote)
🎨 [Figma](https://www.figma.com/file/KX1CGuenK2TlPpvbm6Z9Dk/re.add-social-proof-pattern?node-id=232%3A2659)
---
Adding `<Quote />` component. Can be seen as a sub-component of eventual `<SocialProof />` component https://www.figma.com/file/KX1CGuenK2TlPpvbm6Z9Dk/re.add-social-proof-pattern?node-id=232%3A2659.

feat: init quote component

---

.changeset/sharp-rules-compare.md
packages/consent-manager/index.test.js
packages/consent-manager/index.tsx
packages/consent-manager/loader/index.tsx
packages/consent-manager/props.js
packages/consent-manager/types.ts

🔍 [Preview Link](https://react-components-lpv3b9jp6-hashicorp.vercel.app/components/consentmanager)
---
Adding optional callbacks to detect when users click Manage Preferences and Accept within the ConsentManager toolbar.

feat(ConsentManager): add event callback options

---

package-lock.json
packages/actions/docs.mdx
packages/actions/index.test.js
packages/actions/index.tsx
packages/actions/package.json
packages/actions/props.js
packages/actions/style.module.css
packages/actions/types.ts
packages/author-byline/package.json
packages/quote/index.tsx
packages/quote/package.json
packages/quote/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1202026274556505)
🔍 [Preview Link](https://react-components-git-accomponent-actions-hashicorp.vercel.app/components/actions)
🎨 [Figma](https://www.figma.com/file/7cYgDM618stjYUHDqAfRec/Components?node-id=537%3A891)
---
Introduces `<Actions />`, a simple facade around `<Button />` to make it easier and more consistent to implement two buttons.

feat(component): `<Actions />`

---

package-lock.json
packages/actions/docs.mdx
packages/actions/index.test.js
packages/actions/index.tsx
packages/actions/package.json
packages/actions/props.js
packages/actions/style.module.css
packages/actions/types.ts
packages/author-byline/package.json
packages/intro/docs.mdx
packages/intro/index.test.js
packages/intro/index.tsx
packages/intro/package.json
packages/intro/props.js
packages/intro/style.module.css
packages/intro/types.ts
packages/quote/index.tsx
packages/quote/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1202026147841461)
🔍 [Preview Link](https://react-components-git-accomponent-intro-hashicorp.vercel.app/components/intro)
🎨 [Figma](https://www.figma.com/file/7cYgDM618stjYUHDqAfRec/Components?node-id=543%3A1341)
---
Introduce new `<Intro />` component.

feat(component): `<Intro />`

---

.changeset/eighty-shirts-occur.md
packages/error-view/style.module.css

---
Adjust error view to use `--brand-link` instead of `--highlight-color`.

chore: update error link to use --brand-link

---

package-lock.json
package.json

---
This overrides `react-live` to ensure multiple versions of react are not used (an issue w/ `react-live` < 3)
---
- https://app.asana.com/0/0/1202150832327407

chore: overrides react-live

---

.changeset/cold-hairs-drop.md
packages/content/styles/table.module.css

---
---
- https://app.asana.com/0/0/1201999608008890

fix(content): th align-left default, allow override

---

.changeset/purple-humans-melt.md
package-lock.json
packages/docs-page/package.json

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201999608008890/f)
🔍 [Preview Link](https://react-components-git-zsbump-content-in-docs-page-hashicorp.vercel.app)
---

chore(docs-page): bump react-content for table align fix

---

.changeset/shy-planets-swim.md
.changeset/slimy-toys-sing.md
package-lock.json
package.json
packages/actions/index.tsx
packages/actions/types.ts
packages/intro/index.tsx
packages/intro/package.json
packages/intro/types.ts
packages/next-steps/docs.mdx
packages/next-steps/index.test.js
packages/next-steps/index.tsx
packages/next-steps/package.json
packages/next-steps/props.js
packages/next-steps/style.module.css
packages/next-steps/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1202135879901648)
🔍 [Preview Link](https://react-components-ovih3u11f-hashicorp.vercel.app/components/nextsteps)
---
Introduces new `<NextSteps />` component.
Example usage https://github.com/hashicorp/hashicorp-www-next/pull/2778

feat(component): `<NextSteps />`

---

.changeset/orange-lions-worry.md
.changeset/perfect-swans-hammer.md
.changeset/rich-bears-brake.md
.changeset/shiny-jars-flow.md
.changeset/stupid-items-fold.md
.changeset/stupid-laws-hang.md
.changeset/three-schools-refuse.md
.changeset/wet-papayas-argue.md
.changeset/wild-panthers-nail.md
packages/call-to-action/index.tsx
packages/call-to-action/package.json
packages/code-block/index.tsx
packages/code-block/mdx/index.tsx
packages/code-block/partials/clipboard-button/index.tsx
packages/code-block/partials/code-block-config/index.tsx
packages/code-block/partials/code-tabs/index.tsx
packages/code-block/provider/index.tsx
packages/code-block/provider/use-indexed-tabs.ts
packages/code-block/utils/process-snippet.js
packages/docs-page/render-page-mdx.ts
packages/enterprise-alert/index.tsx
packages/hashi-stack-menu/index.tsx
packages/select-input/index.tsx
packages/sentinel-embedded/index.tsx
packages/terminal/index.tsx
packages/text-split/index.test.js
packages/text-split/index.tsx

---
This PR adds TypeScript types to more packages (mainly those also used in Dev Portal).
The `typecheck` step is expected to fail since we're introducing breaking changes in some downstream packages, and the `typecheck` step uses local versions of packages instead of the version defined in `package.json`.

feat: convert packages to TypeScript

---

.changeset/four-berries-grin.md
packages/notification/docs.mdx
packages/notification/index.test.js
packages/notification/index.ts
packages/notification/notification-with-actions/index.tsx
packages/notification/style.module.css
packages/notification/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1202077202881790)
🔍 [Preview Link](https://react-components-git-acnotification-with-actions-hashicorp.vercel.app/components/notification)
---
Adding a new notification type for consent manager redesign https://github.com/hashicorp/react-components/pull/590

feat(notification): Add `NotificationWithActions` option

---

docs/grid.mdx

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1201789326550430)
🔍 [Preview Link](https://react-components-git-acgrid-docs-hashicorp.vercel.app/docs/grid)
---
Adding basic grid docs.

chore: add basic grid docs

---

.changeset/long-rats-poke.md
package-lock.json
packages/version-select/util.test.ts
packages/version-select/util.ts

---
> **Note**: Related work
> - https://github.com/hashicorp/dev-portal/pull/575

feat(version-select): parse TFE version

---

.changeset/purple-starfishes-decide.md
packages/consent-manager/loader/index.tsx

🔍 [Preview Link](https://react-components-git-nqcm-pass-default-cookies-link-hashicorp.vercel.app)
---
This PR adds a default cookie policy link to the component loader (at `/loader/index.tsx`), much like our default privacy policy link.

feat(ConsentManager): Add default cookie policy link 

---

.changeset/tricky-spiders-run.md
package-lock.json
packages/motion-config/README.md
packages/motion-config/features.ts
packages/motion-config/index.tsx
packages/motion-config/package.json

---
Introduce a `MotionConfig` component that handles lazing loading Framer Motion features. Ref [reduce bundle size](https://www.framer.com/docs/guide-reduce-bundle-size/#available-features).
```tsx
// _app.tsx
import MotionConfig from '@hashicorp/react-motion-config'
export default function App({ Component, pageProps }) {
return (
<MotionConfig>
<Component {...pageProps} />
</MotionConfig>
)
}
```

feat: `<MotionConfig />` component

---

.changeset/brave-badgers-unite.md
packages/combobox/assets/icon-dropdown-gray.svg
packages/combobox/primitives.tsx
packages/combobox/style.module.css
packages/select-input/style.module.css

🔍 [Preview Link](https://react-components-git-dsselect-input-style-hashicorp.vercel.app/)
---
This PR aligns the styling for `@hashicorp/react-select-input` and `@hashicorp/react-combobox`. It takes a few things from the former, and a few things from the latter to make them look nice even when used together.
(the arrow for the country field doesn't appear in this screenshot, but I'm fairly sure that's just due to a local misconfiguration for loading SVG assets; the arrow is _supposed_ to be there)

Align Select and Combobox styling

---

.changeset/famous-zoos-agree.md
package-lock.json
package.json
packages/textarea-input/.npmignore
packages/textarea-input/LICENSE
packages/textarea-input/README.md
packages/textarea-input/docs.mdx
packages/textarea-input/index.test.js
packages/textarea-input/index.tsx
packages/textarea-input/package.json
packages/textarea-input/props.js
packages/textarea-input/style.module.css

🔍 [Preview Link](https://react-components-git-dstext-area-hashicorp.vercel.app/components/textareainput)
---
This PR adds a new `TextareaInput` component which is basically a copy-paste `textarea` version of our existing `TextInput` component.

feat: add TextareaInput component

---

.changeset/cool-bananas-listen.md
packages/product-download-page/index.test.js
packages/product-download-page/package-managers.ts
packages/product-download-page/partials/download-cards/style.module.css

---
This commit updates the Ubuntu/Debian installation instructions to align with the commands listed in the [Official Packaging Guide](https://www.hashicorp.com/official-packaging-guide). It also makes a few small style adjustments to accommodate the longer lines.
Related: https://github.com/hashicorp/terraform/pull/31348

fix(product-download-page): update ubuntu/debian install instructions

---

.changeset/giant-weeks-crash.md
package-lock.json
packages/docs-page/package.json

---
This is related to ensuring the "jump-to-section" code detects `h2 + id` pairs correctly
Test: https://terraform-website-git-kevin-fix-jump-to-section-hashicorp.vercel.app/language#about-the-terraform-language
---
- https://app.asana.com/0/0/1202555103563999

fix(docs-page): move remark-plugins to peer deps

---

.changeset/long-forks-cross.md
packages/button/style.module.css

---
Because `<Button>` renders elements with `z-index: 2`, it needs a new stacking context or else it will cause browsers to render other elements between layers.
This PR fixes this by setting `isolation: isolate` on the root element, which creates a new stacking context at the default `z-index`, preventing interactions with other stacking contexts.

fix(button): render Button with new stacking context

---

.changeset/wet-donkeys-bathe.md
package-lock.json
packages/checkbox-input/index.js
packages/checkbox-input/package.json
packages/text-input/index.js
packages/text-input/package.json
packages/textarea-input/index.tsx
packages/textarea-input/package.json

---
This PR uses [@reach/auto-id](https://reach.tech/auto-id/) to generate SSR-safe `id`s, preventing client/server mismatches.

feat: use @reach/auto-id to generate SSR-safe ids

---

.changeset/sour-snails-remain.md
package-lock.json
package.json
packages/motion-config/features.ts

---
This PR replaces `MotionConfig`'s usage of `domMax` with a custom feature set (basically `domMax - drag`) to reduce bundle size. This shouldn't break the intended usage of `MotionConfig`, but it also supports manual dynamic loading via the following:
```ts
import('@hashicorp/react-motion-config/features').then((mod) => mod.default)
```
Depends on: https://github.com/hashicorp/web-platform-packages/pull/56

feat(motion-config): use custom features configuration

---

.changeset/forty-rocks-wash.md
packages/consent-manager/index.tsx
packages/consent-manager/loader/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/home/1200641486636491/1202502161675793)
---
Expose `saveAndLoadAnalytics` functionality to be used outside of ConsentManager to programmatically set Accept All.
Related Learn PR for usage https://github.com/hashicorp/learn/pull/4497
---
- https://app.asana.com/0/0/1202502161675793

feat(ConsentManager): export saveAndLoadAnalytics function

---

.changeset/two-otters-itch.md
packages/consent-manager/README.md
packages/consent-manager/components/dialog.js
packages/consent-manager/components/dialog.test.js
packages/consent-manager/docs.mdx
packages/consent-manager/index.test.js
packages/consent-manager/index.tsx
packages/consent-manager/loader/index.tsx
packages/consent-manager/props.js
packages/consent-manager/types.ts
packages/consent-manager/util/integrations.js

🎟️ [Asana Task](https://app.asana.com/0/1200641486648086/1202476207672930)
🔍 [Preview Link](https://react-components-git-acconsent-manager-fetch-i-b6a4a5-hashicorp.vercel.app/components/consentmanager)
---
Updates `ConsentManager` to fetch integrations directly from Segment, vs [proxying via web-util-server](https://github.com/hashicorp/web-utility-server/pull/216).
Example pulled from Segments Consent Manager implementation https://github.com/segmentio/consent-manager/blob/370a4b97116d75fbe71692d4e26d70d00222231f/src/consent-manager-builder/fetch-destinations.ts#L9
`utilServerRoot` usage: https://hashicorp-mktg.sourcegraph.com/search?q=context:global+utilServerRoot&patternType=literal
---
- …

chore(ConsentManager): fetch integrations from segment

---

.changeset/slimy-suns-travel.md
package-lock.json
packages/consent-manager/package.json
packages/consent-manager/util/cookies.js

🎟️ [Asana Task](https://app.asana.com/0/1200531701094631/1202476207672917)
🎟️ [Asana Task](https://app.asana.com/0/1200531701094631/1202476207672915)
🔍 [Preview Link](https://react-components-git-acconsent-manager-package-tweaks-hashicorp.vercel.app/components/consentmanager)
---
- Remove events package https://github.com/hashicorp/react-components/commit/a7c56fefee8072093cb749da4d650f7e7f2edaf7
- Remove object-assign package usage https://github.com/hashicorp/react-components/commit/1e274f4fd6349089e57459685a5a3bafcb6e494d

chore(ConsentManager): package maintanance

---

.changeset/spicy-ways-wash.md
packages/notification/core/store.ts

---
Ensure the state in the `useStore` hook is always fresh after subscription.

fix(notification): update local state on subscription

---

.changeset/light-teachers-behave.md
.changeset/tricky-clocks-share.md
package-lock.json
packages/content/styles/ol-ul-lists.module.css
packages/docs-page/package.json

---
Issue raised in slack that ol styles were applying to nested ul list items.
https://hashicorp.slack.com/archives/C5FSPUGDS/p1658506577270079
Fix implemented was to prevent applying li styles to all nested children within ol and only apply to their top level li elements.
**Before:**
**After:**

fix: prevent ol styles applying to nested list items

---

packages/docs-sidenav/index.tsx

---
This is only a perceived problem on some Terraform.io previews that are temporarily merging Cloud-Docs and Enterprise nav-data. Given that some nodes have the same titles and such, the addition of keys here increases the uniqueness and ensures that there are no duplicate key

chore(docs-sidenav): improve key uniqueness

---

.changeset/tough-guests-tell.md

This adds a forgotten changeset from #665

chore: forgotten changeset

---

.changeset/funny-beers-shop.md
packages/toggle/docs.mdx
packages/toggle/index.js
packages/toggle/index.test.js
packages/toggle/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/inbox/1200641486636491/1202077202881790/1202311947610503)
🔍 [Preview Link](https://react-components-git-acwplreskin-toggle-hashicorp.vercel.app/components/toggle)
---
Re-skinning to match updated WPL designs.
<table>
<thead><tr><td></td><td>Default</td><td>Enabled</td><td>Focused</td><td>Disabled</td><td>Dark</td></tr></thead>
<tbody>
<tr>
<td>Before</td>
<td><img width="101" alt="CleanShot 2022-05-20 at 10 16 46@2x" src="https://user-images.githubusercontent.com/825855/169547592-663e510d-1540-468f-8b8f-d667b7ce02c2.png"></td>
<td><img width="100" alt="CleanShot 2022-05-20 at 10 18 41@2x" src="https://user-images.githubusercontent.com/825855/169547748-d74e8882-07fc-4a1f-88d2-d54d0199d799.png"></td>
<td><img width="95" alt="CleanShot 2022-05-20 at 11 …

chore: reskin toggle

---

.changeset/four-baboons-tickle.md
packages/consent-manager/components/dialog.module.css

🔍 [Preview Link](https://react-components-git-acconsent-manager-heading-color-hashicorp.vercel.app/)
---
HashiConf has a global CSS declaration on heading elements to color: white;. This update ensures headings always display in expected color.
View issue: https://hashiconf-git-acconsent-manager-us-opt-in-hashicorp.vercel.app/

fix(consent manager): set headings color

---

.changeset/silent-snails-leave.md
packages/docs-page/render-page-mdx.ts
packages/docs-page/server/loaders/file-system.test.ts
packages/docs-page/server/loaders/file-system.ts
packages/docs-page/server/loaders/remote-content.test.ts
packages/docs-page/server/loaders/remote-content.ts
packages/docs-page/server/loaders/types.ts

feat: call `mdxContentHook` with `scope`

---

.changeset/old-dogs-think.md
package-lock.json
packages/code-block/package.json
packages/combobox/package.json
packages/tabs/package.json

---
This PR updates our components that rely on `@reach` components to use the latest 0.17.0 releases. This is to ensure that only one copy of the `@reach/auto-id` library is installed, since it relies on internal state to allocate IDs.

chore(deps): bump @reach components

---

.changeset/cold-turkeys-speak.md
package-lock.json
package.json
packages/docs-page/package.json

---
This PR bumps `@hashicorp/platform-docs-mdx` to the latest version. The deletions in `package-lock.json` are due to npm being able to dedupe `@reach/auto-id` :tada:
Related https://github.com/hashicorp/react-components/pull/695

chore(deps): bump @hashicorp/platform-docs-mdx

---

.changeset/early-parrots-compete.md
packages/checkbox-input/index.js
packages/checkbox-input/index.test.js

---
This PR updates the CheckboxInput component to display the SVG checkmark when `field.checked` is true, which is the value that changes when used with react-hook-form (as opposed to `value`).

fix(checkbox-input): display checkmark when checked is true

---

.changeset/slow-drinks-yell.md
packages/subnav/style.module.css

Reverts flawed fix from #586 .

fix(subnav): revert flawed fix for overflow issue

---

.changeset/tame-experts-divide.md
packages/close-button/docs.mdx
packages/close-button/index.tsx
packages/close-button/props.js
packages/close-button/style.module.css
packages/close-button/types.ts

🎟️ [Asana Task](https://app.asana.com/0/inbox/1200641486636491)
🔍 [Preview Link](https://react-components-git-acclose-button-size-hashicorp.vercel.app/components/closebutton)
---
Adds new size prop to `<CloseButton />` and introduce `large` size for use in dialogs.

feat(CloseButton): add size option

---

.changeset/unlucky-balloons-itch.md
package-lock.json
packages/card/README.md
packages/card/docs.mdx
packages/card/index.test.js
packages/card/index.tsx
packages/card/package.json
packages/card/props.js
packages/card/style.module.css
packages/card/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202026147841446/1202738878282259/f)
🔍 [Preview Link](https://react-components-git-nq-wpl-card-component-hashicorp.vercel.app/components/card)
---
This PR implements a new `<Card />` component, alongside sub-components consumers can use to compose its contents.

feat(component): `<Card />`

---

.changeset/lazy-queens-beg.md
packages/card/docs.mdx
packages/card/props.js

🔍 [Preview Link](https://react-components-git-nq-improve-card-docs-hashicorp.vercel.app/components/card)
---
This PR makes some improvements to the docs of the `<Card />` component:

chore: Improve <Card /> docs

---

.changeset/light-apricots-compete.md
package-lock.json
packages/intro/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1202026147841446/1202615934597667/f)
🔍 [Preview Link](https://react-components-git-nq-intro-component-updates-hashicorp.vercel.app/components/intro)
---
This PR updates the `<Intro />` component eyebrow to be sentence case, vs uppercase.  This PR also makes a few other changes to better match designs, including font styles and margin.

feat(intro): Component updates

---

.changeset/wet-singers-give.md
packages/docs-page/components/version-select/util.test.ts
packages/docs-page/components/version-select/util.ts

- fix(version-select): version detection
- chore: changeset
---
---
- https://app.asana.com/0/0/1202879642033742

fix(`version-select`): version detection logic

---

.changeset/brown-fans-compare.md
package-lock.json
packages/card/index.tsx
packages/card/package.json
packages/card/style.module.css

🔍 [Preview Link](https://react-components-git-nq-remove-product-meta-dep-hashicorp.vercel.app/components/card)
---
This PR updates `<Card />` dependencies to remove `@hashicorp/platform-product-meta` and add `@hashicorp/flight-icons`

enhance(card): Update dependencies

---

.changeset/serious-experts-smoke.md
packages/consent-manager/components/dialog.module.css

Issue flagged: https://docs.google.com/document/d/1oGOdwsy1wktMTA4UCb2rwtVjKDxLlQiA7Irkl98cMZE/edit?disco=AAAAhEgPW4o
🔍 [Preview Link](https://react-components-git-acconsent-manager-actions-hashicorp.vercel.app/components/consentmanager)
---

chore(ConsentManager): stack actions on mobile

---

.changeset/popular-news-cough.md
packages/subnav/docs.mdx
packages/subnav/index.js
packages/subnav/partials/CtaLinks/style.module.css
packages/subnav/style.module.css

🔍 [Preview Link](https://react-components-git-pbsubnav-center-without-cta-hashicorp.vercel.app/components/subnav)
---
Make sure nav links are always centered on page (before overflow occurs), even when there is not CTA present. 

chore(subnav): Center links

---

.changeset/loud-ducks-whisper.md
package-lock.json
packages/marketo-form/package.json

---
This PR bumps `react-hook-form` to the latest version to fix some TypeScript bugs.

chore(deps): bump react-hook-form

---

.changeset/hungry-bears-tell.md
packages/next-steps/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1202802428287999/1202891942449714/f)
---
As part of Use Case QA, design requested that the `NextSteps` component support a gray background. While it's unclear at the moment if we want to add this functionality to the `NextSteps` component more broadly, we do want to be able to do this specifically for Use Cases. This is easily achieved by wrapping `NextSteps` in a div and setting the `background-color`, however, it was discovered that the non-primary tiles have a transparent background. This results in the tile and `NextSteps` components being the same color which is not desireable.
This PR sets the `background-color` for non-primary tiles to white so that changes to …

Make tile `background-color` white to support different background colors

---

.changeset/tricky-turtles-walk.md
package-lock.json
package.json
packages/products-used/docs.mdx
packages/products-used/index.test.js
packages/products-used/index.tsx
packages/products-used/package.json
packages/products-used/props.js
packages/products-used/style.module.css
packages/products-used/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202802428287999/1203075725709005/f)
🔍 [Preview Link](https://react-components-git-nels-products-usedcreate-f74ae8-hashicorp.vercel.app/components/productsused)
🎨 [Figma](https://www.figma.com/file/VvpEQaWhKQExx9QTWRyayd/Patterns?node-id=677%3A4054)
---
Adds new `<ProductsUsed />` component:
- Bumps `mktg-global-styles` so as to utilize spacing tokens
- Adds docs, props, types and component files for `ProductsUsed`
- Pull down branch and run `npm run test:watch`
- Verify no failed tests
- Navigate to the [component in Preview](https://react-components-git-nels-products-usedcreate-f74ae8-hashicorp.vercel.app/components/productsused)
- Verify component [matches the spec](https://www.figma.com/file/VvpEQaWhKQExx9QTWRyayd/Patterns?node-id=677%3A4054) …

feat: `<ProductsUsed />` component

---

.changeset/empty-snails-suffer.md
packages/standalone-link/style.module.css

🔍 [Preview Link](https://react-components-git-acstandalone-link-animation-hashicorp.vercel.app/components/standalonelink)
---
**Before/After:**
https://user-images.githubusercontent.com/825855/196983640-5c0df5f7-c938-4817-87bb-27fd73295dd7.mp4

StandaloneLink: improve arrow animation

---

.changeset/four-pears-drive.md
package-lock.json
packages/intro/package.json
packages/next-steps/index.tsx
packages/next-steps/package.json
packages/next-steps/style.module.css

🔍 [Preview Link](https://react-components-git-acnext-steps-animation-hashicorp.vercel.app/components/nextsteps)
---
Updates NextSteps Cta styling and animation to match what we are doing in StandaloneLink.
https://user-images.githubusercontent.com/825855/197267885-e6ba9796-5203-4237-8852-c52d00b2f76c.mp4

chore(NextSteps): update cta styling and animation

---

.changeset/little-rats-sort.md
packages/products-used/style.module.css

---
Removes background color from root element to allow being placed on different color backgrounds.

fix(ProductsUsed): remove root background color

---

package-lock.json
packages/card/card.tsx
packages/card/docs.mdx
packages/card/event-card/index.tsx
packages/card/event-card/style.module.css
packages/card/index.tsx
packages/card/package.json
packages/card/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1201874072258661/1203067314227236/f)
🔍 [Preview Link](https://react-components-git-nqncv-eventcard-variant-hashicorp.vercel.app/components/card)
---

feat(Card): `<EventCard />` variant

---

packages/card/card.tsx
packages/card/event-card/index.test.js
packages/card/index.test.js
packages/card/person-card/index.test.js
packages/card/person-card/index.tsx

🔍 [Preview Link](https://react-components-git-{branch-slug}-hashicorp.vercel.app/components/card)
---
This PR adds tests for the new `<Card />` component variants.

feat(Card): Add new tests for variants

---

.changeset/beige-dolls-sort.md
packages/products-used/package.json

---
Fixing an error I am getting in www, when I bumped `mktg-global-styles` to `4.3.1`.
https://vercel.com/hashicorp/hashicorp-www-next/JBgBjhAa92DvN1FhRG1wXJVg95Xt

fix(ProductsUsed): peer dependency version

---

.changeset/shy-ducks-enjoy.md
packages/marketo-form/index.test.js
packages/marketo-form/partials/fields/form-page-url-field/index.tsx
packages/marketo-form/server/api-routes.ts
packages/marketo-form/types.ts

---
This PR reports records with a `status` of `skipped` as errors for Marketo Form submissions. Additionally, it drops query parameters from `form_page_url` fields.

feat: report skipped records as errors

---

.changeset/gold-llamas-build.md
package-lock.json
package.json
packages/inline-video/README.md
packages/inline-video/docs.mdx
packages/inline-video/index.test.js
packages/inline-video/index.tsx
packages/inline-video/package.json
packages/inline-video/props.js
packages/inline-video/style.module.css
packages/inline-video/types.ts

🎟️ [Asana Task](https://app.asana.com/0/0/1203260018123853/f)
🔍 [Preview Link](https://react-components-git-nq-inlinevideo-hashicorp.vercel.app/components/inlinevideo)
---
This PR creates an `<InlineVideo />` component, and bumps `mktg-global-styles` to `4.3.1` so the component can properly render background gradients. Will be used soon in #784 .
Testing for this PR and #784 will be handled in a separate PR after both are merged to the assembly for these components. 

feat(component): `<InlineVideo />`

---

package-lock.json
packages/inline-video/props.js
packages/video-feature/README.md
packages/video-feature/docs.mdx
packages/video-feature/index.test.js
packages/video-feature/index.tsx
packages/video-feature/package.json
packages/video-feature/props.js
packages/video-feature/style.module.css
packages/video-feature/types.ts

🎟️ [Asana Task](https://app.asana.com/0/0/1203253460638593/f)
🔍 [Preview Link](https://react-components-git-nqvf-build-component-hashicorp.vercel.app/component/videofeature)
---
In this PR, the new `VideoFeature` component will be built out:

feat(component): `<VideoFeature />`

---

packages/video-feature/index.test.js

🎟️ [Asana Task](https://app.asana.com/0/1201874072258661/1203253460638593/f)
🔍 [Preview Link](https://react-components-git-nqvf-add-tests-hashicorp.vercel.app/)
---
This PR adds tests for the upcoming `<VideoFeature />` component.

feat(VideoFeature): Add tests

---

.changeset/ten-cats-fail.md

---
Changeset for https://github.com/hashicorp/react-components/pull/793

Add changeset for consent-manager global var updates

---

.changeset/happy-clocks-try.md
package-lock.json
packages/expandable-arrow/docs.mdx
packages/expandable-arrow/index.test.js
packages/expandable-arrow/index.tsx
packages/expandable-arrow/package.json
packages/expandable-arrow/style.module.css

🔍 [Preview Link](https://react-components-git-acexpandable-arrow-hashicorp.vercel.app/components/expandablearrow)
---
Introduces `<ExpandableArrow />` as a component to be use across `<StandaloneLink />`, `<NextSteps />` and within `<Button />`.
```tsx
function Button() {
const [isHovered, setIsHovered] = React.useState(false)
return (
<button
onMouseOver={() => {
setIsHovered(true)
}}
onMouseOut={() => {
setIsHovered(false)
}}
>
{children}
<ExpandableArrow expanded={isHovered} />
</button>
)
}
```

feat(component): `<ExpandableArrow />`

---

.github/workflows/canary-release.yml
.github/workflows/release.yml

---
This PR enables this repository to use new/ centrally located Canary & Release workflow yaml files. These centrally located workflows are triggered when a pull request is created, and new code is pushed (respectively).
These workflows have not been tested locally due to the limitations of GH Actions.

Use reusable workflows from web-platform-packages

---

.github/workflows/canary-release.yml
.github/workflows/release.yml

---
Adds a version to the reusable release workflows. Based on the recommendation [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow), I'm specifying a SHA.

fix(workflows) add version to reusable release workflows

---

.github/workflows/canary-release.yml
.github/workflows/release.yml

chore: bump release workflow versions

---

.changeset/ninety-eyes-shout.md
package-lock.json
package.json
packages/consent-manager/index.test.js
packages/docs-page/components/version-alert/version-alert.test.tsx
packages/docs-page/components/version-select/index.test.tsx
packages/docs-page/index.test.tsx
packages/marketo-form/server/api-routes.ts

---
This PR upgrades the repo from Next v11 😅 to Next v12.3, an important stepping-stone to eventually upgrading to Next v13.
Changes:
- Small tweak to Jest mocks for `useRouter`
- Don't test `async: false` case for consent manager scripts (`async: false` causes scripts to be emitted during the server rendering phase, and are thus untestable in Jest since it only uses client-side rendering)
- Tweak URL param logic for `marketo-form` to handle the new type (`string | string[] | undefined`)

chore(deps): upgrade to next v12.3

---

.changeset/stale-pots-sneeze.md
packages/call-to-action/index.tsx

🔍 [Preview Link](https://react-components-git-pbcall-to-action-add-defa-49178a-hashicorp.vercel.app/components/calltoaction)
---
Update the product prop in `<CallToAction />` optional. Fixes type errors as seen [here](https://vercel.com/hashicorp/hashicorp-www-next/B3u7WGyJiDqhzsnav1Bm6Dam8tKW)

fix(Call To Action): Make `product` optional

---

.changeset/real-insects-begin.md
package-lock.json
packages/inline-video/props.js
packages/inline-video/style.module.css
packages/video-feature/README.md
packages/video-feature/docs.mdx
packages/video-feature/index.test.js
packages/video-feature/index.tsx
packages/video-feature/package.json
packages/video-feature/props.js
packages/video-feature/style.module.css
packages/video-feature/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1201874072258661/1202983318984725/f)
🔍 [Preview Link](https://react-components-git-asm-videofeature-hashicorp.vercel.app/components/video-feature)
---
This is an assembly collecting changes for a new component: `<VideoFeature />` 

[Assembly] `<VideoFeature />`

---

.changeset/tidy-jeans-decide.md
package-lock.json
packages/next-steps/index.tsx
packages/next-steps/package.json
packages/next-steps/style.module.css
packages/standalone-link/index.tsx
packages/standalone-link/package.json
packages/standalone-link/style.module.css

🔍 [Preview Link](https://react-components-git-acimplement-expandable-arrow-hashicorp.vercel.app/)
---
Implements `<ExpandableArrow />` within `<NextSteps />` and `<StandaloneLink />`.
- [NextSteps](https://react-components-git-acimplement-expandable-arrow-hashicorp.vercel.app/components/nextsteps)
- [StandaloneLink](https://react-components-git-acimplement-expandable-arrow-hashicorp.vercel.app/components/standalonelink)

chore(ExpandableArrow): implement within `NextSteps` and `StandaloneLink`

---

.changeset/gold-waves-camp.md
packages/marketo-form/index.ts
packages/marketo-form/partials/fields/country-field/index.tsx

---
This PR exports the `Field` component allowing consumers to benefit from the automatic form field type logic built into the component.

feat: export Field component

---

.changeset/shy-carrots-perform.md
package-lock.json
packages/card/docs.mdx
packages/card/event-card/index.test.js
packages/card/event-card/index.tsx
packages/card/event-card/style.module.css
packages/card/hooks/use-hover.ts
packages/card/index.test.js
packages/card/index.tsx
packages/card/package.json
packages/card/person-card/index.test.js
packages/card/person-card/index.tsx
packages/card/person-card/style.module.css
packages/card/primitives.tsx
packages/card/props.js
packages/card/style.module.css
packages/card/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1201874072258661/1203067314227236/f)
🔍 [Preview Link](https://react-components-git-asm-new-card-variants-hashicorp.vercel.app/components/card)
---
Assembly collecting changes to `<Card />` to support two new variants: `<PersonCard />` and `<EventCard />`.

[Assembly] New variants for `<Card />`

---

.changeset/kind-beers-pay.md
packages/card/docs.mdx

🔍 [Preview Link](https://react-components-git-{branch-slug}-hashicorp.vercel.app/components/card)
---
This PR removes duplicate props docs from `docs.mdx`.

chore(Card): Remove duplicate props docs

---

.changeset/nine-items-boil.md
packages/card/primitives.tsx
packages/card/types.ts

---
This PR refactors types for the `<Card />` component's `Card` primitive, in an effort to fix type errors.

fix(Card): Refactor types for Card primitive

---

.changeset/giant-eels-taste.md
packages/marketo-form/partials/fields/hidden-field/index.tsx

---
Currently, values for hidden fields can only be derived from query parameters. Both the Newsletter Signup Form and Certification mailing list form have hidden fields with default values defined in Marketo and these values need to be passed through when the form is submitted.
This PR adds a check within `<HiddenField />` that sets the value for the field if a default value is provided.

Enable default autofill values for hidden fields

---

.changeset/eight-dots-cheer.md
packages/inline-video/index.tsx
packages/inline-video/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202729477874000/1203402272741275/f)
🔍 [Preview Link](https://react-components-git-acinline-video-optional-gradient-hashicorp.vercel.app/components/inlinevideo?id=NTYwOTcyOTEy&values=IlxuICAgIDxkaXYgc3R5bGU9e3tkaXNwbGF5OiAnZ3JpZCcsIGdyaWRUZW1wbGF0ZUNvbHVtbnM6ICdjYWxjKDUwJSAtIDE2cHgpIGNhbGMoNTAlIC0gMTZweCknLCBnYXA6ICczMnB4J319PlxuICAgICAgPElubGluZVZpZGVvXG4gICAgICAgIHNvbHV0aW9uPVwibmV0d29ya2luZ1wiXG4gICAgICAgIHVybD1cImh0dHBzOi8veW91dHUuYmUvbkowYUk2c0VEUm9cIlxuICAgICAgICBkZXNjcmlwdGlvbj1cIkRlc2NyaXB0aW9uIC0gMiBsaW5lcyB3aXRoIGNoYXJhY3RlciBsaW1pdCBvZiA5MC4gVGVtcHVzIGluIGVnZXN0YXMgc2FnaXR0aXMgbnVsbGEgZmV1Z2lhdFwiXG4gICAgICAvPlxuICAgICAgPElubGluZVZpZGVvXG4gICAgICAgIGdyYWRpZW50UG9zaXRpb249e2ZhbHNlfVxuICAgICAgICB1cmw9XCJodHRwczovL2hhc2hpY29ycC53aXN0aWEuY29tL …

chore(InlineVideo): make gradient optional

---

.changeset/nice-plants-flash.md
package-lock.json
packages/marketo-form/form/index.tsx
packages/marketo-form/package.json
packages/marketo-form/utils.ts

---
This PR adds a call to `segment.identify` on form submissions in `MarketoForm`.

feat: call segment.identify on form submissions

---

.changeset/poor-eggs-rush.md
packages/actions/index.tsx
packages/actions/style.module.css

🔍 [Preview Link](https://react-components-git-acactions-gap-hashicorp.vercel.app/components/actions)
---
Increase column gap when actions contains both a button and a standalonelink
**Before/after**
https://user-images.githubusercontent.com/825855/204890333-01e76b3a-e465-4303-a55a-ba856b32ef6e.mp4

chore(Actions): increase column gap when mixed

---

package-lock.json
package.json

---
[A recent change](https://github.com/hashicorp/swingset/pull/48) to `swingset` was shipped that enables fullscreen content areas. This PR bumps `swingset` to the latest version to enable fullscreen components in `react-components`.
- Navigate to [the preview](https://react-components-iy993ymj5-hashicorp.vercel.app/components/nextsteps)
- Click the fullscreen button in the top right and verify that the sidebar slides away
- Click the button again and verify that the sidebar slides back into view
- Navigate to [a component with the `isFullscreen=true` query param](https://react-components-iy993ymj5-hashicorp.vercel.app/components/callouts?isFullscreen=true)
- Verify that the page …

Bump `swingset` to enable fullscreen content area

---

package-lock.json
package.json

---
This PR bumps `mktg-global-styles` to the latest version. This version includes transparent color tokens.
- Navigate to any page in the preview
- Open dev tools. In the `Style` tab within the `Elements` parent tab, search for `--waypoint-alpha-16`. Verify that the variable displays in the results.

Bump `mktg-global-styles` to enable transparent color tokens

---

.changeset/odd-onions-attend.md
packages/card/style.module.css

---
- Add bottom border to card thumbnail
- Bottom align badges
---
- https://app.asana.com/0/0/1203676337988280

chore(Card): add thumbnail border and badges alignment

---

.changeset/unlucky-pants-own.md
packages/next-steps/docs.mdx
packages/next-steps/index.test.js
packages/next-steps/index.tsx
packages/next-steps/package.json
packages/next-steps/props.js
packages/next-steps/style.module.css
packages/next-steps/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202738955551191/1203512370732554/f)
🔍 [Preview Link](https://react-components-git-nanext-steps-updates-hashicorp.vercel.app/components/nextsteps?isFullscreen=true)
---
This PR updates the `NextSteps` component according to updates in [the spec](https://www.figma.com/file/7cYgDM618stjYUHDqAfRec/Components?node-id=4757%3A31522&t=aZPFJr9zBpNwoozj-1). The changes are as follows:
- enables optional `Badge` in tiles
- enables optional tertiary CTA
- updates tiles to use `secondary` colors
- updates layout according to spec
- Navigate to `NextSteps` in the [Vercel preview deploy](https://react-components-git-nanext-steps-updates-hashicorp.vercel.app/components/nextsteps?isFullscreen=true)
- Validate that the `Badge` implementation matches [the …

feat(`NextSteps`): replace `Intro` CTAs with new CTA, change tile colors and enable badges

---

.changeset/smooth-trainers-teach.md
package-lock.json
packages/form-fields/partials/radio-checkbox/style.module.css

---
This PR adjusts the focus ring on checkbox and radio inputs to only appear when focused via a keyboard interaction thanks to the `:focus-visible` selector. It also adjusts the size.

fix: adjust focus ring behavior

---

.changeset/chatty-moose-bow.md
packages/marketo-form/contexts/FormMetadata.ts
packages/marketo-form/docs.mdx
packages/marketo-form/fixtures/index.ts
packages/marketo-form/form/index.tsx
packages/marketo-form/partials/fields/privacy-policy-field/index.tsx
packages/marketo-form/server/api-routes.ts
packages/marketo-form/server/client.ts
packages/marketo-form/types.ts
packages/marketo-form/utils.test.js

---
This PR adds support for Marketo-driven form localization. Once merged, we will be able to set the language of a form in Marketo and have form elements like the Submit button and Privacy Policy checkbox automatically render in the language of the form.
This includes a breaking change to the props of the MarketoForm component. Instead of the props `formId` and `marketoForm`, we now have `metadata` and `fields`. The `memoizedFormProps` function typically called in `getStaticProps` has been adjusted to account for these new props; if you were previously spreading the return value as props like the following, this change has no impact:
```tsx
<MarketoForm {...marketoForm} />
```
This PR …

feat: add support for Marketo-driven localization

---

.changeset/odd-horses-applaud.md
.github/workflows/canary-release.yml
package-lock.json
packages/consent-manager/package.json

---
This updates `react-consent-manager` to have an explicit dependency on `@hashicorp/flight-icons` since it depends on it.

fix: add flight-icons dep

---

.changeset/small-apples-trade.md
packages/next-steps/style.module.css

🔍 [Preview Link](https://react-components-git-acnext-steps-cta-wrap-hashicorp.vercel.app/components/nextsteps)
---
**BEFORE**
**AFTER**

fix(NextSteps): allow cta to wrap

---

.changeset/orange-knives-buy.md
packages/marketo-form/partials/fields/hidden-field/index.tsx

fix: explicitly set default values for hidden fields

---

.changeset/curly-eyes-shave.md
packages/consent-manager/components/banner.js
packages/consent-manager/components/banner.module.css

🔍 [Preview Link](https://react-components-git-acconsent-manager-banner-text-hashicorp.vercel.app/components/consentmanager)
---
Developer dark mode work includes `color-scheme:dark` on the HTML element when in dark mode. If the text color is not defined, the browser with automatically change the text color to white. This change ensures the text color is always the expected color.
https://user-images.githubusercontent.com/825855/225359101-4a63dc61-6483-4937-b55a-85fc4103575c.mp4

chore(ConsentManager): ensure banner text color is defined

---

.changeset/rare-plums-repair.md
packages/card/style.module.css

fix(Card): thumbnail overflow

---

.changeset/bright-masks-run.md
packages/notification/components/notification/index.tsx
packages/notification/props.js
packages/notification/types.ts

🔍 [Preview Link](https://react-components-git-acnotification-cta-onclick-hashicorp.vercel.app/components/notification)
---
Pass optional onClick handler to Notification CTA to allow adding event trackers to the click event.
Example usage: https://github.com/hashicorp/hashicorp-www-next/pull/3483

feat(Notification): add optional cta onclick handler

---

.changeset/polite-lizards-play.md
packages/alert-banner/fragment.graphql
packages/button/fragment.graphql
packages/image/fragment.graphql
packages/logo-grid/fragment.graphql
packages/section-header/fragment.graphql

---
This PR adds the `id` field to fragments. This allows urql to correctly cache these fragments.

feat: add id field to graphql fragments

---

.changeset/gentle-camels-judge.md
packages/logo-grid/index.tsx

---
This PR allows undefined descriptions for companies in the `LogoGrid` component.

fix: allow undefined descriptions

---

swingset-extensions/usage-details/project-list.js

🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1204310774161160/f)
---
Updates where its used project list.

chore: update project list

---

.changeset/cuddly-cherries-help.md
packages/motion-config/package.json

fix: remove framer-motion as a direct dependency

---

.changeset/thick-nails-play.md

---
This PR is a no-op release of `@hashicorp/react-split-rich-cta-list` because it looks like the npm version of 2.0.3 doesn't have the same set of dependencies as the version in the repo.
```diff
"dependencies": {
"@hashicorp/platform-product-meta": "^0.1.0",
-    "@hashicorp/react-inline-svg": "^1.0.2",
+    "@hashicorp/react-inline-svg": "^6.0.3",
"@hashicorp/react-link-wrap": "^3.0.3",
-    "classnames": "^2.2.6"
+    "classnames": "^2.3.1"
},
```

chore(release): trigger release of updated deps

---

.changeset/hungry-plants-suffer.md
package-lock.json
packages/alert-banner/index.tsx
packages/alert-banner/package.json
packages/subnav/package.json
packages/subnav/partials/CtaLinks/github-stars-link/index.js

---
This PR replaces instances of `@reach/visually-hidden` with `@radix-ui/react-visually-hidden`.

fix: replace Reach VisuallyHidden with Radix

---

.github/workflows/canary-release.yml
.github/workflows/release.yml

Update workflow call params
see https://github.com/hashicorp/web-platform-packages/pull/218

rename `PUBLISH_GITHUB_TOKEN` to `CHANGESETS_PAT`

---

.changeset/tame-bananas-breathe.md
packages/consent-manager/loader/presets/oss.ts
packages/consent-manager/loader/services.ts

- remove optin monster and bizible
- add changeset
---
Opt-in Monster and Bizible are no longer used, so removes from our Consent Manager.

Remove unused consent manager services

---

.changeset/mighty-insects-allow.md
packages/marketo-form/form/index.tsx
packages/marketo-form/server/client.ts

feat: don't use content api

---

.changeset/forty-paws-tease.md
packages/card/card.tsx
packages/card/docs.mdx
packages/card/primitives.tsx
packages/card/props.js
packages/card/types.ts

🔍 [Preview Link](https://react-components-git-pbcard-outbound-link-hashicorp.vercel.app/components/card)
---
This PR adds `isExternal` prop to `<Card />`. If true, the card link will open in a new tab.
This will be used in the www trust center project.

feat(react-card): add isExternal prop

---

.changeset/new-ladybugs-complain.md
packages/alert-banner/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1207142155269495/1207251771790311/f)
🔍 [Preview Link](https://react-components-git-leah-fixalert-banner-z-index-hashicorp.vercel.app/components/alertbanner)
---
This PR adds a z index to the alert banner component. This is to prevent an overlay blur on the alert banner from the subnav dropdowns.

fix: add z-index to alert banner

---

.changeset/swift-doors-clap.md
packages/alert-banner/style.module.css

🔍 [Preview Link](https://react-components-git-leah-fixalert-banner-style-hashicorp.vercel.app/components/alertbanner)
---
This PR fixes some styling bugs for the alert banner. When I was testing previously, I just used the preview link since the canary release was failing. Now that the token has been updated, I tested using the canary release and it looks as expected.

fix: alert banner styling

---

.changeset/seven-pianos-visit.md
.changeset/stale-wasps-shake.md
packages/form-fields/partials/choice-group/index.tsx
packages/form-fields/partials/label/index.tsx
packages/form-fields/partials/radio-checkbox/index.tsx
packages/form-fields/select/index.tsx
packages/form-fields/text/index.tsx
packages/form-fields/textarea/index.tsx
packages/marketo-form/docs.mdx
packages/marketo-form/form/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1205890709355230/1206539228551358/f)
🔍 [Preview Link](https://react-components-git-leah-a11yform-error-aria-hashicorp.vercel.app/)
---
This PR updates the form fields to use `aria-describedBy` for error messages. This is part of the work for our recent accessibility review. I also fixed an error with the error messages when the message contains html (ex. span for email error message in marketoform). This also adds an optional field named formName to MarketoForm. This is used for the aria-label for the component.
[Before link](https://react-components.vercel.app/components/marketoform)
1. Go to [preview](https://react-components-git-leah-a11yform-error-aria-hashicorp.vercel.app/)
2. On the left side, go through each of the form elements and make sure …

a11y: add error text to aria-describedBy for form elements

---

.changeset/heavy-months-compete.md
packages/code-block/analytics.js
packages/code-block/index.test.js
packages/code-block/index.tsx
packages/code-block/partials/clipboard-button/index.tsx
packages/consent-manager/loader/presets/enterprise.ts
packages/consent-manager/loader/services.ts
packages/consent-manager/scripts/segment.tsx
packages/consent-manager/util/integrations.test.js
packages/feedback-form/docs.mdx
packages/feedback-form/index.test.jsx
packages/feedback-form/index.tsx
packages/search/index.js
packages/search/props.js
packages/search/search-box.js
packages/tabs/partials/tab-trigger/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1206176289707208/1207649154492025/f)
---
- Remove references to Heap in the code base. Heap was removed as a service from HashiCorp on June 9th 2024, rendering related code unnecessary
- Remove Heap related attributes and analytics from the following packages:
- code-block
- consent-manager
- feedback-form
- search
- tabs trigger

Remove Heap references
