hashicorp/react-components

packages/subnav/index.js
packages/subnav/index.test.js
packages/subnav/props.js

---
Past me thought he was fixing highlighting in #234, but turns out he broke it for many use cases on www. Adding the new behavior behind a prop, `matchOnBasePath`, to ensure we can still retain the previous, full url match strategy.
Bad behavior can be seen here: https://hashicorp-www-next-git-brkchore-migrate-nextjs-8fb983-hashicorp.vercel.app/products/terraform
Please select one (**required**)
<details>
<summary>Release Notes (<strong>required</strong>)</summary>
</details>
---

fix(subnav): add matchOnBasePath prop

---

packages/docs-sidenav/fixtures/nav-data.json
packages/docs-sidenav/utils/flag-active-nodes.js

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200311175037672/f)
🔍 [Preview Link](https://react-components-git-zsfix-docs-sidenav-dupe-h-94c735-hashicorp.vercel.app/components/docssidenav)
---
This PR fixes an issue where multiple active nodes in the sidebar would result in multiple parent categories being expanded.
This issue arises because docs authors sometimes use `{ title, href }` nodes for internal "alias" links rather than external links, which our design and data model did not account for. Docs authors want these links to be treated as "alias" to the canonical `{ title, path }`-style links.
- Both "canonical" and "alias" links are highlighted
- Any ancestor categories of any "canonical" or "alias" link is expanded and highlighted
- Preview:
- Both "canonical" and …

patch(docs-sidenav): fix duplicate active categories

---

packages/consent-manager/docs.mdx
packages/consent-manager/index.js
packages/consent-manager/index.test.js
packages/consent-manager/package-lock.json
packages/consent-manager/package.json
packages/consent-manager/props.js

📝 [RFC](https://docs.google.com/document/d/12UIDBgpR6lilkFrxQFr7i1zTxCm04szAZkGKSSlgRkI/edit#)
---
This removes the `@segment/in-eu` package and check from our Consent Manager. This change means it will now be shown to all visitors, regardless of their geography. 
Also updates tests, and fixes some small bugs (I think..):
* The `forceShow` prop wasn't working quite right because of the wrong conditional order in `shouldRequireConsent`
* The `preference` object key names were off (e.g. `All` instead of `loadAll`) - prime example of where a TS refactor would help us out here, but that's outside my scope at the moment unfortunately)
1

Show Consent Manager globally

---

packages/combobox/index.tsx
packages/combobox/primitives.tsx
packages/combobox/props.js

🔍 [Preview Link](https://react-components-git-jmcombobox-onblur-hashicorp.vercel.app/components/combobox)
---
This PR adds an `onInputBlur` prop to the default component, and `onBlur` to the `<ComboboxInput />` - I was surprised this was not already in the underlying interface, and am still considering what the proper solution is. I'd like to make sure we give the proper amount of control to consumers at the `<input>` level and expose the right props in the default component without being exhaustive.
1

Add onBlur to combobox

---

packages/content/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1199185162145231/f)
🔍 [Preview Link](https://react-components-git-zsfix-content-blunder-hashicorp.vercel.app)
This PR fixes a facepalm-y issue in our `content` component, where `g-type-body-long` is composed, rather than the correct `g-type-long-body`.

fix(content): fix incorrect body type class

---

packages/product-download-page/index.test.js
packages/product-download-page/index.tsx
packages/product-download-page/partials/download-cards/index.tsx
packages/product-download-page/partials/release-information/style.module.css
packages/product-download-page/props.js
packages/product-download-page/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200743193658743/f)
🔍 [Preview Link](https://react-components-git-zstweak-product-downloads-page-hashicorp.vercel.app)
---
This PR makes non-breaking tweaks to our `@hashicorp/product-downloads-page` component. The primary goal of this PR is to better meet the need for non-product download pages, namely the Vagrant vmware Utility download page (which currently feels dependent on these tweaks).
This minor release adds an optional `pageTitle` prop, and makes minor UX and design tweaks. See #281 for details.
- Adds `pageTitle` prop. This allows an override of the default page title, which is very locked in to being product-only as it relies on `useProductMeta`.
- Prefixes `Binary Download` product card labels with the pretty OS name, …

feat(product-download): support custom title, plus design tweaks

---

packages/tabs/docs.mdx
packages/tabs/index.js
packages/tabs/index.test.js
packages/tabs/partials/TabTriggers/style.css
packages/tabs/props.js

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200778644540399/f)
🎟️ [Asana Task \#2](https://app.asana.com/0/1100423001970639/1200778644540401/f)
---
Adds a new `onChange` prop to `Tabs`. Also fixed up the arrow bug that @alexcarpenter noticed, it was a quick change so threw it in here!
1

feat(Tabs): adds onChange prop to Tabs and fixes arrow bug

---

.changeset/sour-pears-exercise.md
packages/combobox/field/index.tsx
packages/combobox/index.tsx
packages/combobox/primitives.tsx
packages/combobox/props.js
packages/combobox/style.module.css

---
The proposed changes here allow for flexibility on the default  `<Combobox />` re:  `<input>`-related props and some sensible styling defaults for the list of options . More details about this PR outlined below, per use case.
Without the `name` prop, the rendered `<input />` for the Combobox can't be serialized alongside other HTML input elements like you would expect. 
We're using this for a long list of countries, and rather than forcing consumers to use `data-reach-*` selectors in their CSS, we provide a `--combobox-list-max-height` but also a sane default of `40vh` with scrolled overflow so we don't ever visually break the viewport with long lists
Items in this checklist may not may …

Combobox improvements

---

docs/typography.mdx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200604505419290/f)
🔍 [Preview Link](https://react-components-git-zsadd-typography-docs-to-7368db-hashicorp.vercel.app/docs/typography)
---
This PR adds documentation on our typefaces and on our global `g-type-*` utility classes. 

docs: add swingset docs page on typography

---

.changeset/stupid-pumpkins-fail.md
packages/combobox/style.module.css

🔍 [Preview Link](https://react-components-git-accombobox-overflow-hashicorp.vercel.app/components/combobox)
---
This ensures the scroll bar never shows on the x axis and only on the y axis when the list exceeds the default 40vh max height.

Combobox overflow 

---

.changeset/nasty-bears-shop.md
packages/docs-page/components/version-alert/index.jsx
packages/docs-page/components/version-alert/version-alert.test.tsx
packages/docs-page/docs.mdx
packages/docs-page/index.test.tsx
packages/docs-page/index.tsx
packages/docs-page/package.json
packages/docs-page/props.js
packages/version-select/index.test.tsx
packages/version-select/util.test.ts
packages/version-select/util.ts

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200973126209666/f)
🔍 [Preview Link](https://react-components-c8n9ub4bu-hashicorp.vercel.app/components/docspage)
---
This adds the newer VersionSelect component to `DocsPage`, and removes dependency on `@hashicorp/versioned-docs`
This adds a `showVersionSelect` prop on `DocsPage` — you can now toggle this via _the live editor_
This exports a `removeVersionFromPath` util from version-select
This backfills some test coverage 🧪 

feat: DocsPage w/ new VersionSelect

---

.changeset/afraid-melons-collect.md
packages/combobox/package.json

📝 To-Do
---
`formik` must be a peer dependency so we do not install another copy of it. `<ComboboxField />` leverages the shared `FormikContext` via `useField`, so of course this needs to be using the same `formik`.
Hit this error when attempting to use `<ComboboxField />` over on another project. As an optional dependency, `npm` went ahead and installed a different `formik` local to this package (seen in the error).

[Combobox] Move Formik to peerDeps

---

.changeset/silent-ads-work.md
packages/version-select/index.test.tsx
packages/version-select/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201068752304258/f)
---
From the `changeset`
> Fixed a bug with `version-select` where navigating to a latest version, while on the latest version caused the site to be pushed to "/latest", which is unintended.
> 
> Also added minor improvements to not call Next.js router `push` when selecting a version that is the same as the current version.
> 
> Added test coverage.

fix(version-select): Navigation bug + minor improvements

---

.changeset/rude-keys-chew.md
packages/alert/index.tsx

---
Based on the implementation, both `state` and `textColor` are optional props. Adjusting this based on this as well as usage encountered in sites.

fix(Alert): make state and textColor optional

---

.changeset/three-bags-hear.md
packages/select-input/index.js
packages/select-input/index.test.js

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201091209139212/f)
---
This fixes a bug where an object was being passed to Downshift's `key`
- ![image](https://user-images.githubusercontent.com/26389321/135533004-05fb41b8-bffc-4e9f-af14-814c74f22e4c.png)

fix(select-input): incorrect Downshift key

---

.changeset/weak-chairs-judge.md
packages/version-select/index.test.tsx

🎟️ [-]()
🔍 [-](-)
---
Fixed by https://github.com/hashicorp/react-components/pull/369 (select-input 4.0.4)
This adds more test coverage
Smoke test: https://waypoint-none31bq2-hashicorp.vercel.app/commands which is using `select-input 4.0.4` under the hood

test(version-select): coverage for URL sync

---

.changeset/funny-tigers-shop.md
package-lock.json
packages/search/package.json

---
`unist-util-visit` was recently upgraded to serve ESM. This is great, except we currently run this script in a CJS node environment. I'm gonna revert for now until we have tooling in place to run node scripts which leverage ESM.
Example failure: https://app.circleci.com/pipelines/github/hashicorp/vagrant/2025/workflows/0467ada7-c83c-4090-8c25-16ede596f0d3/jobs/2033

fix(search): revert unist-util-visit dep

---

.changeset/unlucky-poets-wink.md
packages/docs-sidenav/utils/validate-route-structure/index.js
packages/docs-sidenav/utils/validate-route-structure/index.test.js

---
Small bugfix to follow up #336 !

DocsPage: fix validation error when using heading nodes

---

.changeset/tender-lies-type.md
packages/docs-page/docs.mdx
packages/docs-page/index.tsx
packages/docs-page/props.js
packages/docs-page/server/generate-static-paths.ts
packages/docs-page/server/generate-static-props.ts

🎟️ [-]()
🔍 [-](https://react-components-git-{branch-slug}-hashicorp.vercel.app)
---
This updates logic to treat `process.env.ENABLE_VERSIONED_DOCS` as `string`
- environment variables are always strings.

fix(docs-page): process.env.ENABLE_VERSIONED_DOCS is `string`

---

.changeset/sixty-humans-fix.md
packages/subnav/style.module.css

---
When the subnav is in sticky mode, and you have a permalink on the page, the headline ends up scrolling underneath the menu. This little css thingy prevents that from happening. It used to be implemented on each of our documentation sites hanging off the global `.g-subnav` but that no longer works because of css modules, and honestly it should have been part of this component anyway since I can't really imagine a scenario where you would want your permalinks to be hidden by this component, so I think this should do the trick. Tested on vault docs website and it worked wonderfully.

Add permalink spacing handling to subnav when its sticky

---

.changeset/honest-clocks-kick.md
packages/product-features-list/index.js

🔍 [Preview Link](https://react-components-git-acproduct-features-list-heading-hashicorp.vercel.app/components/productfeatureslist)
---
A11y fix to ensure sequential order of headings h2 -> h3 instead of h2 -> h4

Fix: make `<ProductFeaturesList>` headings h3

---

.changeset/twenty-otters-promise.md
packages/select-input/index.js

fix(select-input): safely access value for key

---

.changeset/sharp-crabs-appear.md
.changeset/weak-carrots-fry.md
packages/consent-manager/style.module.css
packages/subnav/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201221128054915/f)
🔍 [Preview Link](https://react-components-git-zshide-consent-manager-print-hashicorp.vercel.app)
---
This PR updates `@hashicorp/react-consent-manager` and `@hashicorp/react-subnav` to ensure both components are hidden in print media.
- fix(consent-manager): hide in print
- fix(subnav): hide in print
- chore(consent-manager): add changeset
- chore(subnav): add changeset

fix: hide subnav and consent-manager in print

---

.changeset/thirty-panthers-admire.md
packages/docs-page/content-api/index.ts

---
This causes `react-docs-page` api client code to throw an error in **development** about missing env vars.

feat(react-docs-page): surface env var error during development

---

.changeset/thick-worms-jam.md
packages/subnav/style.module.css

Relates to
- https://github.com/hashicorp/react-components/pull/391/files
---
This unnests `scroll-margin-top` styling from the `.isSticky` class.
**Preview usage**: https://waypoint-p3qzymh84-hashicorp.vercel.app/commands/logs#usage

fix(react-subnav): scroll-margin-top style

---

packages/docs-page/server/get-node-from-path.test.ts
packages/docs-page/server/loaders/file-system.ts
packages/docs-sidenav/utils/validate-file-paths/index.test.js
packages/docs-sidenav/utils/validate-unlinked-content/index.js
packages/docs-sidenav/utils/validate-unlinked-content/index.test.js

---
This PR updates a few utility functions and tests to account for different path separators on Windows. This ensures that contributors running tests on Windows machines are able to get passing tests.

fix: handle windows paths

---

.changeset/rare-cats-visit.md
packages/docs-page/content-api/__snapshots__/content-api.test.ts.snap
packages/docs-page/content-api/index.ts
packages/docs-page/server/index.ts
packages/docs-page/server/loaders/remote-content.test.ts

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201340096942828/f)
---
This allows us to continue serving a cache/successfully built page, in the event that `getStaticProps` errors.

chore(react-docs-page): throw when data loader gSP errors

---

.changeset/unlucky-icons-sell.md
packages/tabs/partials/tab-trigger/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1126685961643737/1201343249900617)
🔍 [Preview Link](https://react-components-git-ksadds-heap-attribute-tabs-hashicorp.vercel.app/components/tabs)
---
Learn was tracking tab clicks based on the `g-tab-trigger` class; now that this component was converted to used CSS modules, we've lost that tracking. This PR adds a `data-heap-track` attribute to the tab trigger button so we can reinstate the heap event. 

chore(react-tabs): adds heap attribute to tab trigger

---

.changeset/cuddly-impalas-grin.md
packages/subnav/partials/MenuItemsDefault/index.js

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201377046756933/f)
🔍 [Preview Link](https://react-components-git-dsdismiss-subnav-dropdown-hashicorp.vercel.app)
---
Currently, when a dropdown nav menu item triggers a client-side navigation, the dropdown menu isn't dismissed. This PR updates the click handler for dropdown menu items to dismiss the menu when the clicked on element is an anchor tag with a truthy `href` property.
https://user-images.githubusercontent.com/88163/141869113-71ef7210-a4de-4558-9d83-56a4d5477936.mp4
https://user-images.githubusercontent.com/88163/141869146-2d9afc25-7a9e-4767-82d1-19b81144e62d.mp4

Dismiss nav dropdown on anchor click

---

.changeset/breezy-eyes-attend.md
.changeset/itchy-kangaroos-admire.md
packages/docs-page/index.test.tsx
packages/docs-page/index.tsx
packages/docs-page/props.js
packages/search/index.test.js
packages/search/provider.js
packages/search/provider.tsx
packages/search/types.ts

🎟️ [Asana Task](https://app.asana.com/0/0/1201348169048582/f)
🔍 [Preview Link](https://react-components-git-zssearch-flexibility-hashicorp.vercel.app)
This PR exposes `react-search`'s Algolia configuration as an `algoliaConfig` prop that can be passed to `<SearchProvider />`. This change has been proven out in https://github.com/hashicorp/dev-portal/pull/36. 
---
This change is intended to be non-breaking: the new `algoliaConfig` prop is optional, and `react-search` will continue to use `.env` variables if the `algoliaConfig` prop is not available. If neither form of configuration is available, we'll continue to throw an error (as we did previously if `.env` vars were not present).
This PR also modifies `react-docs-page` to expose the same configuration variable, which is passed to our …

feat(search): expose algolia config as props, fallback to env

---

.changeset/gold-toys-fry.md
packages/docs-page/render-page-mdx.js
packages/docs-page/server/index.ts
packages/docs-page/server/loaders/file-system.ts

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201465687264527/f)
🔍 [Preview Link](https://react-components-git-zsdocs-page-partials-fix-hashicorp.vercel.app)
---
This PR adds support to `docs-page` server utilities for a new, optional `localPartialsDir` option, when using the `fs` loader.
This option allows better support for varied `content/partials` folder locations relative to the current working directory.
Specifically, in the proposed `dev-portal` local preview setup within product repositories:
- our working directory is `website/cloned-dev-portal`
- the content partials we want to load are in `website/cloned-dev-portal/content/partials`
While we can use `docs-page`'s `localContentDir` option to configuration the filesystem location of our main content files as expected, …

feat(docs-page): add pathToPartials option to fs loader

---

.changeset/odd-numbers-lay.md
packages/content/style.module.css
packages/content/styles/iframe.module.css

🎟️ [Asana Task](https://app.asana.com/0/0/1201476871035774/f)
🔍 [Preview Link](https://react-components-git-dscontent-iframe-hashicorp.vercel.app/components/content?id=LTEyMjU5MjYwNTA&values=IjxDb250ZW50XG4gIHByb2R1Y3Q9J3RlcnJhZm9ybSdcbiAgY29udGVudD17PGlmcmFtZSBzcmM9XCJodHRwczovL3d3dy55b3V0dWJlLmNvbS9lbWJlZC9oOTcwWkJnS0lOZ1wiIGZyYW1lQm9yZGVyPXswfSBhbGxvd0Z1bGxTY3JlZW4gd2lkdGg9ezE5MjB9IGhlaWdodD17MTA4MH0gLz59XG4vPiI%3D)
---
This PR adds a `max-width: 100%` rule to iframe elements so that they don't cause the content container to be wider than expected.

Constrain iframes to width of container

---

.changeset/five-comics-perform.md
packages/search/index.test.js
packages/search/search-box.js

---
The `aria-activedescendant` must be set to an element ID as defined by the [spec](https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#aria-activedescendant). Setting it to an empty string renders the prop in the HTML, whereas setting it to `undefined` results in the property not being set on the element.

fix: only set aria-activedescendant to an active ID

---

.changeset/eighty-pigs-agree.md
packages/subnav/partials/MenuItemsOverflow/index.js

🎟️ [Asana Task](https://app.asana.com/0/0/1201476871035773/f)
---
This extends the behavior added in https://github.com/hashicorp/react-components/pull/426 to the MenuItemsOverflow component, which is used on mobile devices.

fix: dismiss overflow dropdown on anchor click

---

.changeset/hot-swans-think.md
packages/docs-page/server/index.ts
packages/docs-page/server/loaders/file-system.test.ts
packages/docs-page/server/loaders/file-system.ts

---
This PR allows the caller to pass in a `githubFileUrl` function to the `@hashicorp/react-docs-page` `generateStaticProps` method, which overrides the default `githubFileUrl` property on the returned pages. This gives special projects (like terraform-website) the ability to link to docs stored outside a `website` folder.

Allow caller to override `githubFileUrl` in `generateStaticProps`

---

.changeset/big-plums-travel.md
packages/docs-page/index.tsx
packages/version-select/docs.mdx
packages/version-select/index.test.tsx
packages/version-select/index.tsx
packages/version-select/util.test.ts
packages/version-select/util.ts
swingset-extensions/next-router-debugger/index.tsx

- feat(version-select): handle multipart basePath
- chore: changeset
🎟️ [-]()
🔍 https://react-components-git-kevin-version-select-basepath-hashicorp.vercel.app/components/versionselect
---

feat(version-select): handle multipart basePath

---

.changeset/silver-spies-dream.md
packages/subnav/partials/TitleLink/index.js

🔍 [Preview Link](https://react-components-git-nqsubnav-enable-hashicorp-logo-hashicorp.vercel.app/components/subnav)
---
This PR adds support for using our company logo in the `<TitleLink />` component of `<Subnav />`.  Now a consumer can pass `titleLink={{ text: 'hashicorp' }}` to the `<Subnav />` and the HashiCorp logo will appear, much like how our other product options operate.

enh: Add support for 'hashicorp' titleLink logo

---

.changeset/tricky-kiwis-sin.md
packages/product-download-page/partials/download-cards/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/0/1200164665926606/f)
🔍 [Preview Link](https://react-components-git-nqdownloader-margin-update-hashicorp.vercel.app)
---
This PR reduces the bottom margin of the `.downloadCards` element in the `product-download-page` component, to better align its spacing with the rest of the page.

enhancement: Reduce product-download-page card margin

---

.changeset/afraid-penguins-yell.md
packages/product-download-page/utils/downloader.ts

As discussed with the release engineering team internally ([ref](https://hashicorp.slack.com/archives/CKJV0JLRX/p1639432100139300)), removing the pretty arch specifiers for 32/64 bit on downloads pages!

update wording on 32/64-bit arch downloads

---

.changeset/tough-moose-grab.md
packages/docs-page/docs.mdx
packages/docs-page/index.test.tsx
packages/docs-page/index.tsx
packages/docs-page/server/loaders/remote-content.test.ts
packages/docs-page/server/loaders/remote-content.ts
packages/glossary-page/index.js

- chore(DocsPage): hide VersionAlert
- chore: changeset
🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201619796458628/f)
---
This updates `DocsPage` to **not** display the `VersionAlert` if the version in the path happens to be the "latest" version
Depends on 
- https://github.com/hashicorp/mktg-content-workflows/pull/103
- manually update DB data

chore: Hide VersionAlert on DocsPage

---

.changeset/spicy-geckos-type.md
packages/content/styles/table.module.css

---
The adjustment to add x-axis overflow scrolling on tables caused some weird behavior:
(see https://www.consul.io/commands/join)
Largely this appears to be because of the change to `display: block` so that we could apply a `max-width`, but this is causing other issues.
I've changed the display to `inline-block`, which appears to fix the width issue while still allowing us to retain the x-axis scrolling.
I had to remove the `margin-bottom` because margin collapsing does not apply to `inline-block` elements, per spec.
After:
---
- To see the specific tasks where the Asana app for GitHub is …

fix(react-content): Fix mismatch between table width and child element widths

---

.changeset/tender-apples-cross.md
packages/hashi-stack-menu/index.jsx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200616393941326/f)
🔍 [Preview Link](https://react-components-git-dsright-click-brand-subnav-hashicorp.vercel.app/)
---
This PR adds a context menu handler to the HashiCorp logo in HashiStackMenu to redirect the user to HashiCorp's brand page when right-clicking.

feat: redirect to brand page when right-clicking HashiCorp logo

---

package-lock.json
packages/error-view/index.tsx
packages/error-view/versioned-view.tsx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201630522524202/f)
---
**Note: this PR is targeting @zchsh's branch to add the error-view package. [The PR](https://github.com/hashicorp/react-components/pull/493)**
Adds a specific error view for use on docs sites with versioned docs. It's effectively a full, custom implementation of `pages/_error.tsx`. Implementation looks something like this:
```tsx
import { VersionedErrorPage } from '@hashicorp/react-error-view/versioned-view'
export default VersionedErrorPage
```

adds versioned error view

---

packages/error-view/README.md
packages/error-view/__tests__/use-404-redirects.test.tsx
packages/error-view/index.tsx
packages/error-view/package.json
packages/error-view/use-404-redirects.ts

---
This PR adds a new hook called `use404Redirects` to the exports of `@hashicorp/react-error-view`. When this hook is used on a 404 page, it checks to see if the current URL results in a 200 status from the server with a `pathname` different to the current value. If so, it performs a client-side redirect to that new `pathname`.
This hook allows us to cover the edge-case where the Next Router _thinks_ a URL can be resolved solely on the client, and thus doesn't run any redirects.

Add `use404Redirects` hook to error-view exports

---

.changeset/lucky-worms-tease.md

---
It turns out, patch version ranges are very restrictive when you're on `0.0.x`
```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: sentinel-docs@1.0.0
npm ERR! Found: @hashicorp/sentinel-embedded@0.0.14
npm ERR! node_modules/@hashicorp/sentinel-embedded
npm ERR!   @hashicorp/sentinel-embedded@"0.0.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @hashicorp/sentinel-embedded@"^0.0.9" from @hashicorp/react-sentinel-embedded@1.0.3
npm ERR! node_modules/@hashicorp/react-sentinel-embedded
npm ERR!   @hashicorp/react-sentinel-embedded@"1.0.3" from the root project
```
Items in this checklist may not may not apply to …

chore(sentinel-embedded): trigger publish for deps update

---

.changeset/many-birds-smile.md
packages/code-block/partials/code-lines/index.js

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200794405240290/f)
🔍 [Preview Link](https://react-components-git-zsfix-code-manual-copy-hashicorp.vercel.app/components/codeblock)
---
This PR fixes an issue where selecting and then copying code in Firefox would result in a lack of newlines in the copied code. It also fixes an issue where empty newlines were not always reproduced correctly when rendering.
This work has been proven out via:
- https://github.com/hashicorp/web-platform-packages/pull/18
- Pulls in this work on `@hashicorp/react-code-block` via canary release from this PR
- Cuts canary release of `@hashicorp/platform-docs-mdx`
- …

fix(code-block): fix manual code copy issue

---

.changeset/big-bikes-deliver.md
packages/docs-page/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201819583341205)
---
Wrap the content rendered by `DocsPage` in `CodeTabsProvider` to ensure that tab syncing can function across multiple instances of `CodeTabs`.
Validated here: https://vault-git-brkfeat-code-tabs-sync-hashicorp.vercel.app/docs/get-started/developer-qs

feat(docs-page): wrap docs page content with CodeTabsProvider

---

.changeset/olive-otters-reflect.md
package-lock.json
packages/consent-manager/package.json

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1200794405240290/f)
🔍 [Preview Link](https://react-components-git-zsadd-events-dep-to-consent-manager-hashicorp.vercel.app)
---
This PR attempts to fix the following NextJS deploy error from hashicorp/nomad#12117:
I'm not sure why this error came up at the specific time it did, but it seems to be related to [this change in Webpack > 5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed). This fix adds the `events` package as an explicit dependency of `@hashicorp/react-consent-manager` in an attempt to avoid this error.

fix(consent-manager): add events dependency

---

.changeset/eighty-walls-promise.md
packages/docs-page/temporary_jump-to-section.js

---
This PR refactors the headline extraction logic of our Jump to Section code to ignore H2 elements on DocsPage that aren't tagged with the appropriate Remark plugin.

Support non-jump-to-section tagged H2 in DocsPage

---

.github/workflows/canary-release.yml

> N / A -- 🎟️ Asana Task
🔍 [Preview Link](https://react-components-git-zsspecify-node-16-hashicorp.vercel.app)
---
This PR specifies node `16.x` in our `canary-release` workflow in order to avoid errors like https://github.com/hashicorp/react-components/runs/5428667254?check_suite_focus=true .

fix: specify node 16 in canary-release workflow

---

.changeset/rare-eggs-return.md
packages/product-download-page/index.tsx
packages/product-download-page/partials/download-cards/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1201915132498455/f)
🔍 [Preview Link](https://react-components-git-zsupdate-downloads-page-hashicorp.vercel.app)
---
This PR makes minor modifications to `@hashicorp/react-product-download-page` in order to more accurately mark `merchandisingSlot` and `enterpriseMode` as optional props. This prevents consumers who do not want to use features behind these props from having to pass `merchandisingSlot={null}` and `enterpriseMode={false}` respectively.
This PR relates to hashicorp/dev-portal#153 - see https://github.com/hashicorp/dev-portal/pull/153#discussion_r819108688. I've proven out a pre-release in hashicorp/dev-portal#158.

feat(product-download-page): make optional props optional

---

.changeset/thirty-files-study.md
packages/code-block/docs.mdx
packages/code-block/partials/code-tabs/index.js
packages/code-block/partials/code-tabs/index.test.js
packages/code-block/partials/code-tabs/partials/tabs-as-dropdown/index.js
packages/code-block/partials/code-tabs/partials/tabs-as-dropdown/style.module.css
packages/code-block/partials/code-tabs/partials/tabs-as-tabs/index.js
packages/code-block/partials/code-tabs/partials/tabs-as-tabs/style.module.css
packages/code-block/partials/code-tabs/style.module.css

🎟️ [Asana Task - Alignment](https://app.asana.com/0/1100423001970639/1201866381269498/f)
🎟️ [Asana Task - Children validation fix](https://app.asana.com/0/1100423001970639/1201881376116200/f)
🔍 [Preview Link](https://react-components-git-zscode-tabs-alignment-hashicorp.vercel.app/components/codeblock)
---
This PR...
This PR also fixes a bug in `CodeTabs` related to validation of children elements, which prevented some use in JSX. With this fix in place, `CodeTabs` should correctly validate the use of `CodeBlock` children in JSX.
---
- https://app.asana.com/0/0/1201881376116200
- …

feat(code-block): left-align tabs, fix valid children issue

---

.changeset/tiny-games-pull.md
package-lock.json
packages/product-download-page/package.json
packages/product-download-page/utils/downloader.ts

This fixes a type error encountered in Dev-Portal (reported by @ashleemboyer), by adding `@types/semver` and fixing `semverValid` usage
---
- https://app.asana.com/0/0/1201944395382131

fix(product-download-page): type error when @types/semver is present

---

.changeset/great-pugs-help.md
packages/docs-page/index.tsx

---
This PR modifies the TypeScript types for `DocsPage` to allow passing `null` for `canonicalUrl`.
Packer plugins are rendered with an undefined `canonicalUrl`, which normally works since the JSON serialization that's performed as part of `getStaticProps` doesn't serialize undefined properties. However, when attempting to pass a typecheck, we're requiring a string value for `canonicalUrl`. Setting it to `undefined` doesn't work since Next can detect that you've defined a property as `undefined`, and returns an error. This change allows passing in a `null` to signify that you don't have a `canonicalUrl` and still satisfy the typechecker.
Items in this checklist may not may not apply to …

Allow null values for `canonicalUrl`

---

.changeset/tender-terms-mix.md
packages/docs-page/server/index.ts
packages/docs-page/server/loaders/file-system.ts
packages/docs-page/server/loaders/remote-content.ts

---
This updates both the `Remote` and `FileSystem` data loaders to accept a function for `remarkPlugins`. The function is called with the current pages params

feat(docs-page): support passing remarkPlugins as a fn

---

.changeset/large-comics-change.md
packages/docs-page/server/loaders/file-system.ts
packages/docs-page/server/loaders/remote-content.ts

---
Supports a `latestVersionRef` option for `RemoteContentLoader` which forces the "latest" version to fetch from a specific ref.
e.g. if we're viewing `waypointproject.io/docs` and we pass `latestVersionRef: 'dev-portal'`, the loader would attempt to load content from `/api/content/waypoint/doc/dev-portal/docs` instead of whatever the latest version is (maybe `/api/content/waypoint/doc/v0.7.x/docs`).
I also fixed a bug with the recent addition to support passing `remarkPlugins` as a function.

feat(docs-page): support latestVersionRef option to RemoteContentLoader

---

.changeset/metal-coins-reply.md
packages/radio-group/types.ts

🔍 [Preview Link](https://react-components-git-acradio-group-optional-props-hashicorp.vercel.app/components/radiogroup)
---
- Makes layout and variant props optional
- Fixes onChange type

chore(radiogroup): prop type update

---

.changeset/tough-laws-smile.md
packages/actions/docs.mdx
packages/actions/index.tsx
packages/actions/props.js
packages/actions/types.ts
packages/author-byline/docs.mdx
packages/author-byline/index.test.js
packages/author-byline/index.tsx
packages/author-byline/props.js
packages/author-byline/types.ts
packages/intro/docs.mdx
packages/intro/index.tsx
packages/intro/props.js
packages/intro/style.module.css
packages/intro/types.ts
packages/quote/docs.mdx
packages/quote/index.test.js
packages/quote/index.tsx
packages/quote/props.js
packages/radio-group/docs.mdx
packages/radio-group/index.test.js
packages/radio-group/index.tsx
packages/radio-group/props.js
packages/radio-group/radio-input/index.test.js
packages/radio-group/radio-input/index.tsx
packages/radio-group/radio-input/types.ts
packages/radio-group/types.ts

Align light/dark mode prop naming based on system preferences naming `appearance`.
**Previews:**
- [Actions](https://react-components-jnjaw36nz-hashicorp.vercel.app/components/actions)
- [AuthorByline](https://react-components-jnjaw36nz-hashicorp.vercel.app/components/authorbyline)
- [Intro](https://react-components-jnjaw36nz-hashicorp.vercel.app/components/intro)
- [Quote](https://react-components-jnjaw36nz-hashicorp.vercel.app/components/quote)
- [RadioGroup](https://react-components-jnjaw36nz-hashicorp.vercel.app/components/radiogroup)

chore: convert to `appearance` prop for light/dark modes

---

.changeset/chilled-hairs-reply.md
packages/docs-page/server/loaders/remote-content.test.ts
packages/docs-page/server/loaders/remote-content.ts

This adds a `navDataPrefix` option to our `RemoteContentLoader`.
This helps to address a previous assumption that `basePath` would always be the same for `doc` and `nav-data` lookups from our API, which is not necessarily going to be the case going forward.
---

feat(RemoteContentLoader): navDataPrefix option

---

.github/workflows/release.yml

This PR updates `release.yml` to use a service account token `CHANGESETS_PAT`. This is necessary due to recent GitHub security update disallowing actions to open / approve PRs

use `CHANGESETS_PAT`

---

.changeset/sweet-apples-fetch.md
packages/subnav/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1202161542547331/1202193674176938/f)
🔍 [Preview Link](https://react-components-git-zspatch-subnav-overflow-hashicorp.vercel.app)
---
This PR fixes an issue in `@hashicorp/react-subnav` where, before overflow detection, subnav might cause horizontal overflow in some situations.
Note: this fix was initially made to address an issue with layout shift on mobile. The specific issue has since been resolved in another way, but this fix still felt worth merging.

fix(subnav): dot-io layout shift issue

---

.changeset/shy-houses-unite.md
packages/code-block/index.test.js
packages/code-block/index.tsx
packages/code-block/partials/clipboard-button/index.tsx
packages/code-block/props.js

🎟️ [Asana Task](https://app.asana.com/0/1201903760348480/1202114097062999/f)
🔍 [Preview Link](https://react-components-git-zscode-block-on-copy-hashicorp.vercel.app/components/codeblock)
---
This PR implements an `onCopyCallback` prop for `code-block`. This callback is called after `code-block`'s Copy button is clicked.
Note that this callback is _not_ called as a direct result of the `onClick` on the button - instead, we wait until we can confirm whether the copying of text was successful.

feat(code-block): onCopyCallback

---

.changeset/polite-pears-wash.md
packages/docs-page/index.tsx

---
Adds an `optInBanner` prop to docs page so we can render an opt-in banner for dev portal. Intentionally made the prop specific as we'll eventually be pulling this code into dev-portal and or deprecating it, so it doesn't make sense to try and make this a "generic" feature.
Related dev-portal PR: https://github.com/hashicorp/dev-portal/pull/470

feat(docs-page): add optInBanner prop to docs-page

---

.changeset/clever-zebras-shout.md
.changeset/wise-terms-heal.md
packages/code-block/partials/clipboard-button/index.tsx

🔍 [Preview Link](https://react-components-git-ambadjust-on-copy-callback-hashicorp.vercel.app)
---
The new `onCopyCallback` function in `CodeBlock` was being invoked on initial load. This PR moves the invocation of this callback to the `onClick` handler for the rendered `<button>` used for copying.
- I've also added some empty lines between blocks of the `onClick` handler and added curly braces to one-line if statements. Both of these sets of additional changes were made to improve the readability of this code.
A draft PR was created to test these changes in `dev-portal`. See [dev-portal#555](https://github.com/hashicorp/dev-portal/pull/555).

[code-block] Moving invocation of onCopyCallback

---

.changeset/nine-items-end.md
packages/code-block/partials/code-tabs/partials/tabs-as-dropdown/index.js
packages/code-block/partials/code-tabs/partials/tabs-as-dropdown/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1202114367927919/1202439831418533/f)
🔍 [Preview Link](https://react-components-git-zstweak-code-block-dropdown-alignment-hashicorp.vercel.app)
🏷️ Downstream pre-release test: https://github.com/hashicorp/dev-portal/pull/615
---
This PR fixes alignment of code-tabs dropdown when no heading is present.
Easiest way to review new styles & behaviour is likely downstream in this `dev-portal` PR, which uses a pre-release from this PR:
- https://github.com/hashicorp/dev-portal/pull/615

fix(code-block): code tabs dropdown alignment

---

.changeset/nervous-gorillas-hear.md
packages/error-view/__tests__/use-error-page-analytics.test.tsx
packages/error-view/use-error-page-analytics.ts

Update our error page analytics event to be consistently named.
This will make Analysis against this event easier, as the way that the event is currently structured produces a new table in our analysis systems, which makes broad error analysis nearly impossible to do.
We're only sending along the error code itself, as Segment will automatically send two context values which will be useful for error analysis: `context_page_url` (the URL where the error happened) and `context_page_referrer` (the URL before the error happened, which will be useful for sniffing out the source of 404s).

Rename event to error page loaded

---

.changeset/selfish-points-raise.md
packages/head/helpers/is-absolute-url.ts
packages/head/index.test.js
packages/head/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1202415308965256/f)
🔍 [Preview Link](https://react-components-git-zsmeta-tags-for-social-share-cards-hashicorp.vercel.app)
---
This PR adds validation to try to ensure that the `image` prop provided to `@hashicorp/react-head` is an absolute URL. This is to match the Open Graph protocol, which notes [All valid URLs that utilize the https:// or https:// protocols](https://ogp.me/#url).

feat(hashi-head): validate props.image, add twitter:description

---

.changeset/tall-spoons-greet.md
packages/docs-page/util/index.ts
packages/docs-page/util/util.test.ts

---
This fixes a bug where a frontend URL was being converted to an incorrect content API url
- /enterprise/v202206-1/support
- https://content.hashicorp.com/api/content/ptfe-releases/doc/v2022.6.1/enterprise/v202206-1/support
```console
[GET] /enterprise/v202206-1/support
10:36:18:02
2022-06-30T14:36:18.253Z	e224ee77-631b-4fc5-a2ce-f47460eec718	ERROR	Failed to generate static props: ContentApiError: Failed to fetch: https://content.hashicorp.com/api/content/ptfe-releases/doc/v2022.6.1/enterprise/v202206-1/support
at fetchDocument (/var/task/.next/server/chunks/935.js:12159:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
at async …
```

feat(docs-page): strip tfe version from pathparams

---

.changeset/stupid-days-remain.md
packages/notification/core/store.ts

---
Fixed a tricky timing bug with the initial state in `useStore` and `memoryState`. Basically, `memoryState` can update in between when `useState` is called in `useStore` and when the store listener is added in the `useEffect`. Changing `useState` to use a lazy initializer fixes this by deferring the initial reading of `memoryState` until it's needed.

fix(notifications) timing bug with memoryState and listener

---

.changeset/stale-bulldogs-design.md
package-lock.json
packages/notification/components/notification-with-resource/index.tsx
packages/notification/components/notifications/index.tsx
packages/notification/core/notification.ts
packages/notification/types.ts

Based on whether or not the notification contains interactive content, render the notification with `role="alert"` for toasts and `role="alerDialog"` for dialogs.
This is based off the work HDS team has done with their [toast implementations](https://design-system-components-hashicorp.vercel.app/components/toast).
And confirmation from HDS team https://hashicorp.slack.com/archives/C7KTUHNUS/p1657818549189699?thread_ts=1657652997.846709&cid=C7KTUHNUS
```tsx
notification() // defaults to toast type
notification.toast() // type = toast with role = alert
notification.dialog() // type = dialog with role = alertDialog
```
https://user-images.githubusercontent.com/825855/179763363-611d8b2c-0f60-4864-b44e-f0dff14a8951.mp4
Items in this checklist may not may not apply to your PR, but please …

feat: introduce notification types

---

.changeset/twenty-ads-sort.md
packages/docs-page/components/version-alert/version-alert.test.tsx
packages/docs-page/index.tsx

This updates `docs-page` to pass the `projectName` prop to the `VersionAlert` component.

feat(docs-page): pass `projectName` to version-alert

---

.changeset/fifty-mayflies-kiss.md
packages/docs-page/components/version-alert/index.tsx
packages/docs-page/components/version-alert/version-alert.test.tsx
packages/docs-page/index.test.tsx
packages/docs-page/index.tsx

This updates the version-alert to use the `display` value that is returned from the ContentAPI

feat: refactor version-alert text

---

.changeset/polite-shrimps-refuse.md
packages/docs-page/index.tsx

---
Adjusts conditional to apply `s.versionedDocsOffset` to use `showVersionSelect` instead of the env var. This will line up the version select element with the search element visually.

fix(docs-page): use correct boolean to determine versionedDocsOffset

---

.changeset/nine-squids-teach.md
packages/docs-page/server/loaders/file-system.test.ts
packages/docs-page/server/loaders/file-system.ts
packages/docs-page/server/loaders/remote-content.test.ts
packages/docs-page/server/loaders/remote-content.ts

This enables local version-faking when using the `FS` content loader.
You can force a "version" into state by inserting a version like `v1.1.x` or `v202207-1` after the subpath in the URL.

feat(docs-page): local version faking

---

.changeset/swift-birds-hear.md
packages/docs-page/server/loaders/file-system.test.ts
packages/docs-page/server/loaders/file-system.ts
packages/docs-page/server/loaders/remote-content.test.ts
packages/docs-page/server/loaders/remote-content.ts
packages/docs-page/server/loaders/types.ts

---
This exposes the previously unused [mdxContentHook](https://github.com/hashicorp/react-components/blob/main/packages/docs-page/render-page-mdx.ts#L15) option on our loader interfaces.

feat(docs-page) expose `mdxContentHook`

---

.changeset/lazy-pets-run.md
packages/head/index.test.js
packages/head/index.tsx

---
Update the absolute URL check on the `image` prop to only happen if the `image` prop is a string. This ensures the head component can still retain its fallback behavior in cases where we're specifying a default image higher up in the component tree.

fix(react-head): only check if image prop is absolute if it exists

---

.changeset/green-cats-attack.md
packages/textarea-input/index.tsx

---
Fixes the TypeScript types for the `field.ref` and `form.errors` properties to be compatible with react-hook-form.

Fix TypeScript types for react-hook-form compatibility

---

.changeset/blue-ladybugs-scream.md
packages/tabs/index.tsx

---
Fixes a scenario where a Tabs instance which has a nested Tabs instance in multiple children with a different number of tabs throws an error when switching between top-level tabs.
Repro:
* Navigate to https://learn.hashicorp.com/tutorials/boundary/hcp-getting-started-install?in=boundary/hcp-getting-started
* Select "Linux"
* Select the last tab
* Select "Windows"
* See the error page

fix(tabs): activeIdx of nested tabs

---

.changeset/stupid-lions-grab.md
packages/error-view/__tests__/use-404-redirects.test.tsx
packages/error-view/use-404-redirects.ts

🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1202865459293217/f)
---
It was recently discovered that, across our various web properties, we make the following call:
`window.analytics.track(window.location.href, { ... } )`
The first parameter of the `track` method is used downstream in our various data warehouses to create a new table. Since we're using `window.location.href`, we're creating a table for _every_ URL that 404s. This is not ideal for analytics.
This PR leverages the new `useErrorPageAnalytics` hook (see [this PR](https://github.com/hashicorp/web-platform-packages/pull/86)) for pushing 404-related data to Segment. This PR replaces the `window.analytics.track` call on the 404 page with said hook.
Items in this checklist may not may not apply to your PR, but please …

Use `useErrorPageAnalytics` hook on 404 page

---

.changeset/yellow-jars-lie.md
packages/docs-sidenav/index.tsx

---
Updated the `onClickOutside` handler to also validate that the click event was not from the menu toggle button. I'm not sure why this started happening, potentially a React internal update that came with React 18.
Fixes the mobile menu not opening: https://www.consul.io/docs
To validate locally in `dev-portal`:
* Copy the contents of `packages/docs-sidenav/index.tsx`
* In `dev-portal`:
* replace the contents of `node_modules/@hashicorp/react-docs-page/node_modules/@hashicorp/react-docs-sidenav/index.tsx` with what you coped from the previous step
* clear next's local cache: `rm -rf .next`
* run the app locally in a .io context: `npm run start:consul`
* validate that the mobile menu …

fix(docs-sidenav): fix bug in mobile menu toggling

---

.changeset/rare-plums-crash.md
packages/intro/index.tsx

[Preview](https://react-components-git-acintro-description-html-hashicorp.vercel.app/components/intro?id=NDUwNTkxNzgz&values=IjxJbnRyb1xuICBleWVicm93PVwiVm9sdXRwYXQgZW5pbSBmdXNjZSB0ZW1wb3JcIlxuICBoZWFkaW5nPVwiU2l0IGV0IGJpYmVuZHVtIGFkaXBpc2Npbmcgbm9uIG1pIHRlbXBvciBuZXF1ZVwiXG4gIGRlc2NyaXB0aW9uPVwiPHA%2BQ3JhcyB1bGxhbWNvcnBlciBkdWlzIG51bmMgdmVsaXQgY29tbW9kbyBldGlhbS4gQXVjdG9yIHRpbmNpZHVudCBwZWxsZW50ZXNxdWUgdWxsYW1jb3JwZXIgbmlzaSBpbnRlZ2VyLiBNYXR0aXMgcXVpc3F1ZSBwb3J0YSB2ZWwgZXVpc21vZCB2ZWxpdCBpZC4gQXJjdSBiaWJlbmR1bSBuZXF1ZSBhZGlwaXNjaW5nIGV0IGNyYXMgZmFjaWxpc2kuPC9wPlwiXG4gIGFjdGlvbnM9e3tcbiAgICBjdGFzOiBbXG4gICAgICB7XG4gICAgICAgIHRpdGxlOiAnVmlldyB0dXRvcmlhbHMnLFxuICAgICAgICB1cmw6ICcvdHV0b3JpYWxzJyxcbiAgICAgICAgdmFyaWFudDogJ3ByaW1hcnknXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB0aXRsZTogJ1ZpZXcgZG9jd …

fix(Intro): description check for HTML

---

.changeset/orange-impalas-act.md
package-lock.json
package.json
packages/subnav/package.json

🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1203093711604797/f)
🔍 [Preview Link](https://react-components-git-nels-choresbump-mktg-logos-hashicorp.vercel.app/components/subnav)
---
It was recently discovered that the old Vault logo is currently being used in the `Subnav` component. This PR updates packages so as to use the new logos (logo change [here](https://github.com/hashicorp/mktg-logos/pull/9)).
- Navigate to the [`Subnav` in Preview](https://react-components-git-nels-choresbump-mktg-logos-hashicorp.vercel.app/components/subnav)
- Set `text` in the `titleLink` prop to `HashiCorp Vault`
- Verify that the correct logo is displayed:

Chore: Bump `mktg-logos` to v1.3.2

---

.changeset/polite-gifts-smell.md
packages/marketo-form/form/index.tsx

---
This PR adjusts the options to the `reset` method for `MarketoForm` to retain modified values regardless of their `isDirty` state. This is primarily needed to retain values set to fields via the `setValue` method, which doesn't affect the `isDirty` property.

fix(marketo-form): keep modified values when recalculating initial state

---

.changeset/shy-eyes-scream.md
packages/code-block/docs.mdx
packages/code-block/partials/code-lines/style.module.css
packages/code-block/utils/process-snippet.js

🎟️ [Asana Task][task]
🔍 [Preview Link][preview]
---
Support copy-button copying of shell-session snippets with multiple single-line commands. 
Support select-copy-paste copying of shell-session snippets by setting `user-select: none` CSS on `.shell-symbol` tokens.
> **Note**: pre-releases has been tested in hashicorp/dev-portal#1149.
[task]: https://app.asana.com/0/1202097197789424/1203067508838442/f
[preview]: https://react-components-git-zscode-block-multi-command-copy-hashicorp.vercel.app/components/codeblock

feat(code-block): support multiple single-line cmd copy

---

.changeset/fast-peas-repeat.md
packages/marketo-form/form/index.tsx

---
This is a follow up to https://github.com/hashicorp/react-components/pull/743 that restores `keepDirtyValues` to ensure that values that are set via `initialValues` are retained alongside values that are set via `setValue`.

fix: keep dirty values when resetting form

---

.changeset/forty-tips-matter.md
package-lock.json
package.json
packages/card/docs.mdx
packages/card/index.tsx
packages/card/package.json
packages/card/props.js
packages/card/style.module.css
packages/card/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202802428287999/1203049731246701/f)
🔍 [Preview Link](https://react-components-git-nels-cardadd-product-badg-3c55a7-hashicorp.vercel.app/components/card)
---
This PR enables `<ProductBadge />` support to the `<Card />` component. Couple of call-outs:
- The spec for the `Card` component displays the `hasDot` variant of `ProductBadge`. Given that and a preference to be a bit restrictive, we force that variant in the code.
- Similarly, the code does not allow `ProductBadge` to be a composable child.
- Navigate to the [preview link](https://react-components-git-nels-cardadd-product-badg-3c55a7-hashicorp.vercel.app/components/card)
- Add the following prop to any of the cards in the Code Editor:
`productBadges={{badges: [{ productName: 'waypoint'}]}}`
- …

feat: Add `<ProductBadge />` support to `<Card />` component

---

.changeset/popular-gorillas-compare.md
packages/head/index.tsx

---
This PR updates `react-head` to specifically import the types from `react` that it needs rather than relying on a global `React` type being present.

fix: specifically import React types

---

.changeset/itchy-flowers-whisper.md
package-lock.json
packages/code-block/partials/code-tabs/index.tsx

🎟️ [Asana Task](https://app.asana.com/0/1202097197789424/1203204105610771/f)
🔍 [Preview Link](https://react-components-git-zsfix-code-tabs-language-hashicorp.vercel.app)
---
Fixes a bug where `shell-session` snippets within `CodeTabs` would copy correctly via the `Copy` button, but would still include the `$` character when selected and copied by clicking and dragging.
Removes a `className` attribute that passed a non-existent className, which also dropped any incoming classNames. This was originally intended to prevent the possibility of custom styling via MDX, but has the side-effect of dropping the `language-<language>` class. That language class was unused for the most part (highlighting happens on the server!), but has become important for full functionality since #736 shipped.
This …

fix(code-block): fix language-undefined in MDX CodeTabs

---

packages/consent-manager/util/cookies.js
packages/consent-manager/util/cookies.test.js

🎟️ [Asana Task](https://app.asana.com/0/1202097197789424/1203274026595792/f)
---
Exports a const that lets us know if preferences have been loaded by reading a global variable set within `loadPreferences()`. The motivation here is to use this in order to prevent re-runs of `saveAndLoadAnalytics()` in our web properties. See [this draft PR for example](https://github.com/hashicorp/dev-portal/pull/1317/files#diff-b359798aa474d6e3d6c2a75fe11ed4d0bb12fed48592453f433524ed0be5ab5dR52). In this example, we want to run `saveAndLoadAnalytics()` only after sign in. So here we'd replace `if (!loadPreferences())` to `if (!preferencesSavedAndLoaded())`. It is essentially the same check but it provides the data without …

feat(consent manager): Add function to check if preferences are loaded

---

.changeset/ninety-dingos-guess.md
packages/intro/index.tsx
packages/intro/props.js
packages/intro/types.ts

🔍 [Preview Link](https://react-components-git-acintro-description-type-hashicorp.vercel.app/components/intro)
---
Allows ReactNodes to be rendered within the description.
On some recent work for the brand landing page, we made use of structured text field, which required the type update.
```tsx
<Intro
appearance="dark"
heading={whitepaper.heading}
description={
<StructuredText data={whitepaper.description.value} />
}
actions={{
ctas: [
{
title: whitepaper.cta.text,
href: whitepaper.cta.url,
},
],
}}
/>
```

feat(Intro): allow ReactNodes within description

---

.changeset/three-pots-kneel.md
packages/marketo-form/form/index.tsx
packages/marketo-form/partials/field-wrapper/index.tsx
packages/marketo-form/partials/fields/checkbox-field/index.tsx
packages/marketo-form/partials/fields/country-field/index.tsx
packages/marketo-form/partials/fields/email-field/index.tsx
packages/marketo-form/partials/fields/privacy-policy-field/index.tsx
packages/marketo-form/partials/fields/select-field/index.tsx
packages/marketo-form/partials/fields/telephone-field/index.tsx
packages/marketo-form/partials/fields/text-field/index.tsx
packages/marketo-form/partials/fields/textarea-field/index.tsx

---
This PR surfaces a field's ID in the `FieldWrapper` component in the form of a data attribute. There are cases where we need control of the order of the form's fields. Creating a data attribute for the field's ID gives us specific, readable selectors to use in CSS (versus general, DOM element selectors).
- Navigate to the [MarketoForm in the Preview](https://react-components-git-nels-marketo-formextend-t-fe5bc2-hashicorp.vercel.app/components/marketoform)
- Pick a field in the form and inspect the top-level `div`
- Verify that there is a `data-field-id` attribute with a value of a field ID.
Items in this checklist may not may not apply to your PR, but please consider each item …

Add data attribute to `FieldWrapper` to enable field-level styling

---

.changeset/proud-walls-flow.md
packages/consent-manager/util/cookies.js

---
Add a check before setting `preferencesLoaded` global variable. We were previously setting `preferencesLoaded` to true before the cookies were actually set. This affected our check following dev portal sign ins

fix(consent-manager): check preferences before setting global var

---

.changeset/eighty-elephants-switch.md
packages/code-block/partials/hidden-copy-content/index.js

---
Adjust `HiddenCopyContent` to only render after hydration as occurred. This helps avoid some tricky hydration issues, and also avoids duplicative markup being shipped from the server. As the element is only used by the copy-to-clipboard interaction, it's safe to defer rendering.

fix(code-block): only render HiddenCopyContent after hydration

---

.changeset/red-jokes-allow.md
packages/inline-video/index.tsx

---
Unless `react-player` is loaded on the client-side using dynamic/no-ssr or `useEffect`, React will panic with a hydration error (see [this issue](https://github.com/cookpete/react-player/issues/1474)). 
This PR updates the `InlineVideo` component to conditionally render the player if the `window` not `undefined`.

Render `react-player` only if the `window` exists

---

.changeset/three-ravens-trade.md
packages/related-content/docs.mdx
packages/related-content/index.tsx
packages/related-content/style.module.css

---
When `<RelatedContent />` was created, it used the `<StandaloneLink />` component for a CTA. However, the WPL spec for `<RelatedContent />` does not utilize `<StandaloneLink />` and instead uses its own, custom link.
This PR removes the `<StandaloneLink />` and adds an `anchor` element.
- Navigate to [the preview
](https://react-components-git-naupdate-relatedcontent-hashicorp.vercel.app/components/relatedcontent)
- Verify that the CTA link matches the spec for light and dark:

Replace `<StandaloneLink />` with anchor element in `<RelatedContent />`

---

.changeset/beige-zebras-think.md
packages/actions/index.tsx
packages/actions/props.js
packages/actions/style.module.css
packages/actions/types.ts
packages/intro/index.tsx
packages/intro/props.js

🔍 [Preview Link](https://react-components-git-acintro-centering-hashicorp.vercel.app/components/actions?id=MTk3MjQ5MjI3Mw&values=IjxBY3Rpb25zXG4gIGxheW91dD1cInN0YWNrZWRcIlxuICBhbGlnbm1lbnQ9XCJjZW50ZXJcIlxuICBjdGFzPXtbXG4gICAge1xuICAgICAgdGl0bGU6ICdWaWV3IHR1dG9yaWFscycsXG4gICAgICBocmVmOiAnL3R1dG9yaWFscycsXG4gICAgfSxcbiAgICB7XG4gICAgICB0aXRsZTogJ1ZpZXcgZG9jdW1lbnRhdGlvbicsXG4gICAgICBocmVmOiAnL2RvY3MnLFxuICAgIH1cbiAgXX1cbi8%2BIg%3D%3D)
---
Stacked CTAs within intro were always left aligned. This PR enables centering actions when Intro is using `textAlignment="center"` and ctas stacked.
**Before:**
**After:**
Needed for building out CRO io home hero alt component: https://github.com/hashicorp/dev-portal/pull/1510
Items in this checklist may not may not apply to your PR, but please consider …

fix(Intro): actions centering

---

.changeset/angry-suns-melt.md
packages/quote/docs.mdx
packages/quote/index.tsx
packages/quote/props.js
packages/quote/style.module.css
packages/quote/types.ts

🔍 [Preview Link](https://react-components-git-acquote-text-size-hashicorp.vercel.app/components/quote)
---
Adds option to control the text sizing.
Following similar prop naming convention as Intro `headingSize` options.
Used on new early careers landing page https://github.com/hashicorp/hashicorp-www-next/pull/3309

feat(Quote): add text size option

---

.changeset/chilly-plums-share.md
packages/marketo-form/form/index.tsx
packages/marketo-form/index.test.js
packages/marketo-form/server/api-routes.ts
packages/marketo-form/utils.test.js
packages/marketo-form/utils.ts

---
This PR treats skipped records as errors. Basically, this prevents calling the onSuccess handler if any of the records of the response are skipped.

fix: return error on skipped records

---

.changeset/chilly-bikes-scream.md
packages/enterprise-alert/index.tsx

---
When used inline, `EnterpriseAlert` currently renders a `div` as its root element. This is problematic when used in MDX specifically, as it will most likely be a child of a `p`. Per the spec, `p` elements cannot contain block-level elements and so the HTML is invalid. This results in React hydration errors.
I've updated `EnterpriseAlert` to render `span` as its root element if the `inline` prop is passed to fix this.

fix(EnterpriseAlert): render span when inline

---

.changeset/rotten-bats-pretend.md
package-lock.json
packages/marketo-form/form/index.tsx

---
Technically emails in the form of `label@domain` are valid, but Marketo doesn't accept these emails. This PR adjusts our validation regex to require a domain+tld combination to reduce the instances where we submit an invalid form.

fix: require emails to have domains

---

.changeset/gold-avocados-raise.md
packages/card/primitives.tsx
packages/card/style.module.css

🔍 [Preview Link](https://react-components-git-acfix-card-thumbnail-sizing-hashicorp.vercel.app/components/card)
---
Fixes issue with card thumbnail sizing due to Next13 image updates.
**Before**
**After**
Preview the fix: https://github.com/hashicorp/hashicorp-www-next/pull/3427

fix(Card): thumbnail sizing

---

.changeset/blue-trees-talk.md
package-lock.json
packages/image/fragment.graphql

---
This PR updates the GraphQL fragment for `react-image` to fetch image dimensions, making it suitable for use in instances where we're passing the fragment's data to `next/image`.

feat: update GraphQL fragment to fetch image dimensions

---

.changeset/beige-walls-doubt.md
package-lock.json
packages/card/person-card/index.test.js
packages/card/person-card/index.tsx

---
This PR adds support for generic links for `PersonCard`, allowing HashiCorp Ambassadors to link to their personal websites.

feat: add support for generic links for PersonCard

---

.changeset/young-bags-dream.md
packages/subnav/partials/CtaLinks/index.js
packages/subnav/props.js

🔍 [Preview Link](https://react-components-git-acsubnav-ctalinks-onclick-hashicorp.vercel.app/components/subnav)
---
Adds the ability to supply an `onClick` prop to subnav `ctaLinks` item.
View usage example https://github.com/hashicorp/dev-portal/pull/1718

feat(Subnav): pass ctalinks onclick through to cta buttons

---

.changeset/stale-plants-divide.md
package-lock.json
packages/placeholder/style.module.css

🔍 [Preview Link](https://react-components-git-nqplaceholder-fix-shine-height-hashicorp.vercel.app/components/placeholder)
---
This PR fixes an issue with `.box` `background-size` causing the "shine" animation not to fill the box height on Safari/iOS.
Context: `.box` had no explicit height value set for its `background-size` property, and values default to auto if not set. However, in Safari/iOS, the `auto` for the height value is not the height of the container, but (from observation) the value set for width. This behavior seems to have caused the "shine" to only reach `75%` of the box's height in Safari/iOS. Setting the height value to an explicit `100%` mitigates the issue.

fix(placeholder): Shine height on Safari/iOS

---

.changeset/fuzzy-bugs-learn.md
packages/call-to-action/index.tsx

---
This PR updates the `theme` prop for `CallToAction` to accept `gray` in line with usage [here](https://github.com/hashicorp/hashicorp-www-next/blob/main/pages/community/office-hours/index.jsx#L56).

fix: update ts type to allow theme="gray"

---

.changeset/six-dingos-pay.md
.changeset/thirty-pugs-listen.md
packages/alert/index.tsx
packages/docs-page/components/version-alert/index.tsx

---
This PR marks the `product` prop of `Alert` as optional to match [this](https://github.com/hashicorp/hashicorp-www-next/blob/main/pages/community/index.jsx#L57-L62) usage. `useProductMeta` is allowed to be invoked with `undefined`, which will then use the `product` config from the nearest `ProductMetaProvider`.

fix: mark product as optional

---

.changeset/silent-news-shave.md
packages/form-fields/partials/label/style.module.css

🎟️ [Slack thread](https://hashicorp.slack.com/archives/C02T80JTNS2/p1679957367718719)
---

chore(Label): remove tomato usage

---

.changeset/late-rats-complain.md
package-lock.json
packages/card/person-card/index.test.js
packages/card/person-card/index.tsx

---
This PR adds support for `mailto:` links to `PersonCard`. Additionally, it refactors the `Icon` component to rely on a `Map` and `memo` instead of several `if` statements.

feat: add support for mailto links in PersonCard

---

.changeset/good-icons-argue.md
.changeset/tasty-parrots-battle.md
package-lock.json
package.json
packages/docs-page/components.ts
packages/docs-page/index.tsx
packages/form-fields/package.json
packages/form-fields/partials/choice-group/index.tsx
packages/form-fields/partials/radio-checkbox/index.tsx
packages/form-fields/select/index.tsx
packages/form-fields/text/index.tsx
packages/form-fields/textarea/index.tsx
swingset-extensions/playground/index.tsx

---
This PR removes `@reach/auto-id` in favor of React.useId in `react-form-fields`. The remaining packages using `@reach/auto-id` are no longer being maintained.
As a part of this PR, `@types/react` was updated to v18, and `react-docs-page` was adjusted to account for the breaking changes (namely the deprecation of the `FunctionalComponent` utility type).

feat: remove @reach/auto-id

---

.changeset/grumpy-islands-repair.md
packages/consent-manager/index.test.js
packages/consent-manager/index.tsx
packages/consent-manager/scripts/custom.tsx

---
This PR fixes the (most recent consent-manager change)[] and filters the `additionalServices` by their optional `shouldLoad` field in the main component rather than the `<CustomScript />` component. This solves an issue where we were still seeing the service in the `<ConsentPreferences />` dialog when `shouldLoad()` was false
See this canary version in use [here](https://github.com/hashicorp/web/pull/280)

fix(consent-manager): filter additional services in main component

---

.changeset/witty-snakes-pull.md
package-lock.json
packages/marketo-form/form/index.tsx

---
This PR updates the validation logic of `marketo-form` to treat all-whitespace values as invalid. This prevents users from submitting forms with `     ` as a valid value (which Marketo will happily accept).

fix: treat all-whitespace values as invalid

---

.github/workflows/ci.yml
.github/workflows/publish.yml

---
Commit is the result of running HashiCorp's internal version pinning tool, for all GitHub Actions workflows in the repo.
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
Note, this unsolicited PR is a courtesy and has not been tested before submission.  The PR should be evaluated and merged by its responsible team.

Bump all GitHub Actions and pin, to avoid deprecated Node 12

---

.changeset/proud-ravens-marry.md
package-lock.json
packages/form-fields/package.json

---
This PR adds a missing dependency on `classnames` for `react-form-fields`.

fix: add dep on classnames

---

.changeset/hot-students-knock.md
package-lock.json
packages/card/docs.mdx
packages/card/newsroom-card/index.test.tsx
packages/card/newsroom-card/index.tsx
packages/card/primitives.tsx
packages/card/style.module.css

💬 [Slack context](https://hashicorp.slack.com/archives/C031LA4KS4S/p1689102495068719?thread_ts=1689099305.128409&cid=C031LA4KS4S)
🔍 [Preview Link](https://react-components-git-nqcard-update-newsroomcard-hashicorp.vercel.app/components/card)
---
This PR updates `<NewsroomCard />` to support:
- logo-oriented thumbnail styles, via a `<LogoThumbnail />` primitive
- Tweaks to props:
- Category for eyebrow
- Optional thumbnails
Updates have been approved by design via [the end of this Figma thread](https://www.figma.com/file/CaKUjhzM1Q8y2EOCMIoIl1?node-id=2327:7048&mode=dev#490070226).

feat(Card): `<NewsroomCard />` updates

---

.changeset/modern-pianos-draw.md
packages/consent-manager/scripts/custom.tsx
packages/consent-manager/types.ts

🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1204854420026344/f)
🔍 [Preview Link](https://react-components-git-nels-update-consent-manager-hashicorp.vercel.app/components/consentmanager)
This change enables `onLoad` functionality for scripts loaded via the `ConsentManager` component. This will allow us to register an event handler to track events for the Qualified chatbot.

feat(ConsentManager): Enable `onLoad` functionality for scripts

---

.changeset/old-days-rescue.md
package-lock.json
packages/checkbox-input/index.js
packages/checkbox-input/package.json
packages/text-input/index.js
packages/text-input/package.json
packages/textarea-input/index.tsx
packages/textarea-input/package.json

🔍 [Preview Link](https://react-components-git-ksupdate-use-id-hashicorp.vercel.app)
---
`@reach/auto-id` is pinned <= react 17 and this dependency causes conflicts / warnings where react 18 is used. This refactors all uses of `@reach/auto-id` to use the [react version](https://react.dev/reference/react/useId). 

chore: remove @reach/auto-id dep, opt for react's `useId`

---

.changeset/soft-pandas-reflect.md
packages/inline-video/index.tsx
packages/inline-video/types.ts

---
This PR adds the optional `videoClassName` prop so that we can add custom styles that may be needed, such as border, box shadows, etc.
This is related to some updates being made to the dotcom about page.

feat(inline video): add `videoClassName` prop

---

.changeset/dull-bottles-lay.md
packages/card/style.module.css

🎟️ [Discussion](https://hashicorp-www-next-git-gated-content-assembly-hashicorp.vercel.app/on-demand/thank-you?appearance=dark&vercelThreadId=YDNqH)
🔍 [Preview Link](https://react-components-git-pbcard-dark-mode-update-hashicorp.vercel.app/components/card)
---
(EDIT By @EnMod:) This PR updates the colors of dark appearance `<Card />` components to match our new spec, using new tokens.  Prompted by a Vercel thread on using new colors for cards on an upcoming project (discussion thread linked above). Design has approved of the look/feel.

update(react-card): dark mode colors

---

.changeset/old-comics-argue.md
package-lock.json
packages/card/docs.mdx
packages/card/resource-card/index.test.tsx
packages/card/resource-card/index.tsx

🎟️ [Asana Task for request prompting the change](https://app.asana.com/0/1202791227659279/1205347737637312/f)
🔢 [PR on `www` implementing the canary release](https://github.com/hashicorp/web/pull/781)
🔍 [Preview Link](https://react-components-git-nqcard-make-dates-optiona-b3beed-hashicorp.vercel.app/components/card)
🔍 [Preview Link for example usage on `www` (see each case study library item's card)](https://hashicorp-www-next-git-nqwww-hide-case-study-l-583a57-hashicorp.vercel.app/case-studies)
---
This PR updates our `<ResourceCard />` component to make showing the date optional; if no date is passed in, no date (or `|` separator) is shown.

feat(card): Make `date` optional on `<ResourceCard />`

---

.changeset/gold-walls-warn.md
package-lock.json
packages/docs-page/server/get-paths-from-nav-data.ts

---
This PR fixes an empty array comparison. In JavaScript, arrays are objects, and equality comparisons only return true if both sides of the operator refer to the same object. By comparing to an empty array literal, this comparison will always return false. In recent versions of TypeScript, this is considered an error, which prevents builds using this code. This PR changes to compare by length instead.

fix: correctly determine if array is empty

---

.github/workflows/canary-release.yml
.github/workflows/release.yml

🎟️ [Asana Task][task]
Bumps the SHA in references to `web-platform-packages` workflows in `release.yml` and `canary-release.yml`.
To clean up some stray `node 16 will be deprecated` warnings, which are happening due to references to older versions of workflows.
[task]: https://app.asana.com/0/799513369421962/1207374598912342/f

bump sha for workflows referenced from web-platform-packages

---

.changeset/big-beds-promise.md
packages/consent-manager/components/dialog.js
packages/consent-manager/components/dialog.module.css
packages/consent-manager/index.test.js
packages/consent-manager/index.tsx
packages/toggle/index.js

🎟️ Asana Tasks
- [[TF VPAT A11Y] Cookie manager modal does not respond to the ESC key](https://app.asana.com/0/1205890709355230/1205890709355251/f)
- [[TF VPAT A11Y] Cookie manager modal has multiple banner landmarks](https://app.asana.com/0/1205890709355230/1205890709355253/f)
- [[TF VPAT A11Y] Consent manager - Indistinguishable “see more” buttons](https://app.asana.com/0/1205890709355230/1205890709355259/f)
- [[TF VPAT A11Y] Switch toggles missing accessible name](https://app.asana.com/0/1205890709355230/1205890709355261/f)
- [[TF VPAT A11Y] Switches missing keyboard interactions](https://app.asana.com/0/1205890709355230/1205890709355249/f)
Fix a variety of accessiblity issuies around the consent manager:
- Toggles missing accessible names
- see more/less button missing accessible name …

Consent Manager & Toggle a11y fixes

---

.changeset/cyan-panthers-tie.md
package-lock.json
packages/inline-video/style.module.css

🎟️ [Asana Task](https://app.asana.com/0/1208185803237298/1206900259194096/f)
🔍 [Preview Link](https://react-components-git-leah-fixcenter-video-description-hashicorp.vercel.app/components/inlinevideo)
---
This PR centers the description below the video for inline-videos. This came in as a request from the Web Presence Request form. More info on why is in the Asana task.
To fix this, I added `text-align: center` to the video description.
1. Go to preview link
2. At the top, note that the descriptions below the videos are centered

fix: center inline-video description
